class CabinetRunner{
    public static void main(String[] args){

        Cabinet officeCabinet = new Cabinet();
        Cabinet homeCabinet = new Cabinet();
        Cabinet kitchenCabinet = new Cabinet();
        Cabinet bedroomCabinet = new Cabinet();
        Cabinet storageCabinet = new Cabinet();
        Cabinet metalCabinet = new Cabinet();
        Cabinet woodenCabinet = new Cabinet();
        Cabinet portableCabinet = new Cabinet();
        Cabinet miniCabinet = new Cabinet();
        Cabinet largeCabinet = new Cabinet();

        officeCabinet.cabinetColor = "Brown";
        officeCabinet.cabinetHeight = 180;
        officeCabinet.cabinetWidth = 90;
        officeCabinet.cabinetDepth = 50;
        officeCabinet.cabinetWeight = 45.5;
        officeCabinet.isPortable = false;
        officeCabinet.cabinetType = "Office";
        officeCabinet.warrantyYears = 5;
        officeCabinet.countryOfOrigin = "India";
        officeCabinet.discountPercentage = 10;

        System.out.println("Office Cabinet");
        System.out.println("Brand: " + officeCabinet.brand);
        System.out.println("Material: " + officeCabinet.material);
        System.out.println("Shelves: " + officeCabinet.numberOfShelves);
        System.out.println("Price: " + officeCabinet.price);
        System.out.println("Has Lock: " + officeCabinet.hasLock);
        System.out.println("Color: " + officeCabinet.cabinetColor);
        System.out.println("Height: " + officeCabinet.cabinetHeight);
        System.out.println("Width: " + officeCabinet.cabinetWidth);
        System.out.println("Depth: " + officeCabinet.cabinetDepth);
        System.out.println("Weight: " + officeCabinet.cabinetWeight);
        System.out.println("Portable: " + officeCabinet.isPortable);
        System.out.println("Type: " + officeCabinet.cabinetType);
        System.out.println("Warranty: " + officeCabinet.warrantyYears);
        System.out.println("Country: " + officeCabinet.countryOfOrigin);
        System.out.println("Discount: " + officeCabinet.discountPercentage);

        System.out.println("Home Cabinet");
        System.out.println("Brand: " + homeCabinet.brand);
        System.out.println("Material: " + homeCabinet.material);
        System.out.println("Shelves: " + homeCabinet.numberOfShelves);
        System.out.println("Price: " + homeCabinet.price);
        System.out.println("Has Lock: " + homeCabinet.hasLock);
        System.out.println("Color: " + homeCabinet.cabinetColor);
        System.out.println("Height: " + homeCabinet.cabinetHeight);
        System.out.println("Width: " + homeCabinet.cabinetWidth);
        System.out.println("Depth: " + homeCabinet.cabinetDepth);
        System.out.println("Weight: " + homeCabinet.cabinetWeight);
        System.out.println("Portable: " + homeCabinet.isPortable);
        System.out.println("Type: " + homeCabinet.cabinetType);
        System.out.println("Warranty: " + homeCabinet.warrantyYears);
        System.out.println("Country: " + homeCabinet.countryOfOrigin);
        System.out.println("Discount: " + homeCabinet.discountPercentage);

        System.out.println(" Kitchen Cabinet");
        System.out.println("Brand: " + kitchenCabinet.brand);
        System.out.println("Material: " + kitchenCabinet.material);
        System.out.println("Shelves: " + kitchenCabinet.numberOfShelves);
        System.out.println("Price: " + kitchenCabinet.price);
        System.out.println("Has Lock: " + kitchenCabinet.hasLock);
        System.out.println("Color: " + kitchenCabinet.cabinetColor);
        System.out.println("Height: " + kitchenCabinet.cabinetHeight);
        System.out.println("Width: " + kitchenCabinet.cabinetWidth);
        System.out.println("Depth: " + kitchenCabinet.cabinetDepth);
        System.out.println("Weight: " + kitchenCabinet.cabinetWeight);
        System.out.println("Portable: " + kitchenCabinet.isPortable);
        System.out.println("Type: " + kitchenCabinet.cabinetType);
        System.out.println("Warranty: " + kitchenCabinet.warrantyYears);
        System.out.println("Country: " + kitchenCabinet.countryOfOrigin);
        System.out.println("Discount: " + kitchenCabinet.discountPercentage);

        System.out.println(" Bedroom Cabinet");
        System.out.println("Brand: " + bedroomCabinet.brand);
        System.out.println("Material: " + bedroomCabinet.material);
        System.out.println("Shelves: " + bedroomCabinet.numberOfShelves);
        System.out.println("Price: " + bedroomCabinet.price);
        System.out.println("Has Lock: " + bedroomCabinet.hasLock);
        System.out.println("Color: " + bedroomCabinet.cabinetColor);
        System.out.println("Height: " + bedroomCabinet.cabinetHeight);
        System.out.println("Width: " + bedroomCabinet.cabinetWidth);
        System.out.println("Depth: " + bedroomCabinet.cabinetDepth);
        System.out.println("Weight: " + bedroomCabinet.cabinetWeight);
        System.out.println("Portable: " + bedroomCabinet.isPortable);
        System.out.println("Type: " + bedroomCabinet.cabinetType);
        System.out.println("Warranty: " + bedroomCabinet.warrantyYears);
        System.out.println("Country: " + bedroomCabinet.countryOfOrigin);
        System.out.println("Discount: " + bedroomCabinet.discountPercentage);

        System.out.println("Storage Cabinet");
        System.out.println("Brand: " + storageCabinet.brand);
        System.out.println("Material: " + storageCabinet.material);
        System.out.println("Shelves: " + storageCabinet.numberOfShelves);
        System.out.println("Price: " + storageCabinet.price);
        System.out.println("Has Lock: " + storageCabinet.hasLock);
        System.out.println("Color: " + storageCabinet.cabinetColor);
        System.out.println("Height: " + storageCabinet.cabinetHeight);
        System.out.println("Width: " + storageCabinet.cabinetWidth);
        System.out.println("Depth: " + storageCabinet.cabinetDepth);
        System.out.println("Weight: " + storageCabinet.cabinetWeight);
        System.out.println("Portable: " + storageCabinet.isPortable);
        System.out.println("Type: " + storageCabinet.cabinetType);
        System.out.println("Warranty: " + storageCabinet.warrantyYears);
        System.out.println("Country: " + storageCabinet.countryOfOrigin);
        System.out.println("Discount: " + storageCabinet.discountPercentage);

        System.out.println(" Metal Cabinet");
        System.out.println("Brand: " + metalCabinet.brand);
        System.out.println("Material: " + metalCabinet.material);
        System.out.println("Shelves: " + metalCabinet.numberOfShelves);
        System.out.println("Price: " + metalCabinet.price);
        System.out.println("Has Lock: " + metalCabinet.hasLock);
        System.out.println("Color: " + metalCabinet.cabinetColor);
        System.out.println("Height: " + metalCabinet.cabinetHeight);
        System.out.println("Width: " + metalCabinet.cabinetWidth);
        System.out.println("Depth: " + metalCabinet.cabinetDepth);
        System.out.println("Weight: " + metalCabinet.cabinetWeight);
        System.out.println("Portable: " + metalCabinet.isPortable);
        System.out.println("Type: " + metalCabinet.cabinetType);
        System.out.println("Warranty: " + metalCabinet.warrantyYears);
        System.out.println("Country: " + metalCabinet.countryOfOrigin);
        System.out.println("Discount: " + metalCabinet.discountPercentage);

        System.out.println("Wooden Cabinet");
        System.out.println("Brand: " + woodenCabinet.brand);
        System.out.println("Material: " + woodenCabinet.material);
        System.out.println("Shelves: " + woodenCabinet.numberOfShelves);
        System.out.println("Price: " + woodenCabinet.price);
        System.out.println("Has Lock: " + woodenCabinet.hasLock);
        System.out.println("Color: " + woodenCabinet.cabinetColor);
        System.out.println("Height: " + woodenCabinet.cabinetHeight);
        System.out.println("Width: " + woodenCabinet.cabinetWidth);
        System.out.println("Depth: " + woodenCabinet.cabinetDepth);
        System.out.println("Weight: " + woodenCabinet.cabinetWeight);
        System.out.println("Portable: " + woodenCabinet.isPortable);
        System.out.println("Type: " + woodenCabinet.cabinetType);
        System.out.println("Warranty: " + woodenCabinet.warrantyYears);
        System.out.println("Country: " + woodenCabinet.countryOfOrigin);
        System.out.println("Discount: " + woodenCabinet.discountPercentage);

        System.out.println(" Portable Cabinet");
        System.out.println("Brand: " + portableCabinet.brand);
        System.out.println("Material: " + portableCabinet.material);
        System.out.println("Shelves: " + portableCabinet.numberOfShelves);
        System.out.println("Price: " + portableCabinet.price);
        System.out.println("Has Lock: " + portableCabinet.hasLock);
        System.out.println("Color: " + portableCabinet.cabinetColor);
        System.out.println("Height: " + portableCabinet.cabinetHeight);
        System.out.println("Width: " + portableCabinet.cabinetWidth);
        System.out.println("Depth: " + portableCabinet.cabinetDepth);
        System.out.println("Weight: " + portableCabinet.cabinetWeight);
        System.out.println("Portable: " + portableCabinet.isPortable);
        System.out.println("Type: " + portableCabinet.cabinetType);
        System.out.println("Warranty: " + portableCabinet.warrantyYears);
        System.out.println("Country: " + portableCabinet.countryOfOrigin);
        System.out.println("Discount: " + portableCabinet.discountPercentage);

        System.out.println("Mini Cabinet");
        System.out.println("Brand: " + miniCabinet.brand);
        System.out.println("Material: " + miniCabinet.material);
        System.out.println("Shelves: " + miniCabinet.numberOfShelves);
        System.out.println("Price: " + miniCabinet.price);
        System.out.println("Has Lock: " + miniCabinet.hasLock);
        System.out.println("Color: " + miniCabinet.cabinetColor);
        System.out.println("Height: " + miniCabinet.cabinetHeight);
        System.out.println("Width: " + miniCabinet.cabinetWidth);
        System.out.println("Depth: " + miniCabinet.cabinetDepth);
        System.out.println("Weight: " + miniCabinet.cabinetWeight);
        System.out.println("Portable: " + miniCabinet.isPortable);
        System.out.println("Type: " + miniCabinet.cabinetType);
        System.out.println("Warranty: " + miniCabinet.warrantyYears);
        System.out.println("Country: " + miniCabinet.countryOfOrigin);
        System.out.println("Discount: " + miniCabinet.discountPercentage);

        System.out.println(" Large Cabinet");
        System.out.println("Brand: " + largeCabinet.brand);
        System.out.println("Material: " + largeCabinet.material);
        System.out.println("Shelves: " + largeCabinet.numberOfShelves);
        System.out.println("Price: " + largeCabinet.price);
        System.out.println("Has Lock: " + largeCabinet.hasLock);
        System.out.println("Color: " + largeCabinet.cabinetColor);
        System.out.println("Height: " + largeCabinet.cabinetHeight);
        System.out.println("Width: " + largeCabinet.cabinetWidth);
        System.out.println("Depth: " + largeCabinet.cabinetDepth);
        System.out.println("Weight: " + largeCabinet.cabinetWeight);
        System.out.println("Portable: " + largeCabinet.isPortable);
        System.out.println("Type: " + largeCabinet.cabinetType);
        System.out.println("Warranty: " + largeCabinet.warrantyYears);
        System.out.println("Country: " + largeCabinet.countryOfOrigin);
        System.out.println("Discount: " + largeCabinet.discountPercentage);
    }
}