class ControllerRunner{
    public static void main(String[] args){

        Controller gamingController = new Controller();
        Controller officeController = new Controller();
        Controller wirelessController = new Controller();
        Controller bluetoothController = new Controller();
        Controller ergonomicController = new Controller();
        Controller travelController = new Controller();
        Controller compactController = new Controller();
        Controller rgbController = new Controller();
        Controller proController = new Controller();
        Controller advancedController = new Controller();

        gamingController.controllerColor = "Black";
        gamingController.numberOfButtons = 12;
        gamingController.joystickCount = 2;
        gamingController.triggerCount = 2;
        gamingController.controllerWeight = 0.5;
        gamingController.isRechargeable = true;
        gamingController.compatibleDevice = "PlayStation";
        gamingController.warrantyYears = 2;
        gamingController.originCountry = "Japan";
        gamingController.price = 6000;

        System.out.println("Gaming Controller");
        System.out.println("Brand: " + gamingController.controllerBrand);
        System.out.println("Connection: " + gamingController.connectionType);
        System.out.println("Battery: " + gamingController.batteryCapacity);
        System.out.println("Performance: " + gamingController.performanceLevel);
        System.out.println("Vibration: " + gamingController.hasVibration);
        System.out.println("Color: " + gamingController.controllerColor);
        System.out.println("Buttons: " + gamingController.numberOfButtons);
        System.out.println("Joysticks: " + gamingController.joystickCount);
        System.out.println("Triggers: " + gamingController.triggerCount);
        System.out.println("Weight: " + gamingController.controllerWeight);
        System.out.println("Rechargeable: " + gamingController.isRechargeable);
        System.out.println("Device: " + gamingController.compatibleDevice);
        System.out.println("Warranty: " + gamingController.warrantyYears);
        System.out.println("Country: " + gamingController.originCountry);
        System.out.println("Price: " + gamingController.price);

        System.out.println("Office Controller");
        System.out.println("Brand: " + officeController.controllerBrand);
        System.out.println("Connection: " + officeController.connectionType);
        System.out.println("Battery: " + officeController.batteryCapacity);
        System.out.println("Performance: " + officeController.performanceLevel);
        System.out.println("Vibration: " + officeController.hasVibration);
        System.out.println("Color: " + officeController.controllerColor);
        System.out.println("Buttons: " + officeController.numberOfButtons);
        System.out.println("Joysticks: " + officeController.joystickCount);
        System.out.println("Triggers: " + officeController.triggerCount);
        System.out.println("Weight: " + officeController.controllerWeight);
        System.out.println("Rechargeable: " + officeController.isRechargeable);
        System.out.println("Device: " + officeController.compatibleDevice);
        System.out.println("Warranty: " + officeController.warrantyYears);
        System.out.println("Country: " + officeController.originCountry);
        System.out.println("Price: " + officeController.price);

        System.out.println("Wireless Controller");
        System.out.println("Brand: " + wirelessController.controllerBrand);
        System.out.println("Connection: " + wirelessController.connectionType);
        System.out.println("Battery: " + wirelessController.batteryCapacity);
        System.out.println("Performance: " + wirelessController.performanceLevel);
        System.out.println("Vibration: " + wirelessController.hasVibration);
        System.out.println("Color: " + wirelessController.controllerColor);
        System.out.println("Buttons: " + wirelessController.numberOfButtons);
        System.out.println("Joysticks: " + wirelessController.joystickCount);
        System.out.println("Triggers: " + wirelessController.triggerCount);
        System.out.println("Weight: " + wirelessController.controllerWeight);
        System.out.println("Rechargeable: " + wirelessController.isRechargeable);
        System.out.println("Device: " + wirelessController.compatibleDevice);
        System.out.println("Warranty: " + wirelessController.warrantyYears);
        System.out.println("Country: " + wirelessController.originCountry);
        System.out.println("Price: " + wirelessController.price);

        System.out.println("Bluetooth Controller");
        System.out.println("Brand: " + bluetoothController.controllerBrand);
        System.out.println("Connection: " + bluetoothController.connectionType);
        System.out.println("Battery: " + bluetoothController.batteryCapacity);
        System.out.println("Performance: " + bluetoothController.performanceLevel);
        System.out.println("Vibration: " + bluetoothController.hasVibration);
        System.out.println("Color: " + bluetoothController.controllerColor);
        System.out.println("Buttons: " + bluetoothController.numberOfButtons);
        System.out.println("Joysticks: " + bluetoothController.joystickCount);
        System.out.println("Triggers: " + bluetoothController.triggerCount);
        System.out.println("Weight: " + bluetoothController.controllerWeight);
        System.out.println("Rechargeable: " + bluetoothController.isRechargeable);
        System.out.println("Device: " + bluetoothController.compatibleDevice);
        System.out.println("Warranty: " + bluetoothController.warrantyYears);
        System.out.println("Country: " + bluetoothController.originCountry);
        System.out.println("Price: " + bluetoothController.price);

        System.out.println("Ergonomic Controller");
        System.out.println("Brand: " + ergonomicController.controllerBrand);
        System.out.println("Connection: " + ergonomicController.connectionType);
        System.out.println("Battery: " + ergonomicController.batteryCapacity);
        System.out.println("Performance: " + ergonomicController.performanceLevel);
        System.out.println("Vibration: " + ergonomicController.hasVibration);
        System.out.println("Color: " + ergonomicController.controllerColor);
        System.out.println("Buttons: " + ergonomicController.numberOfButtons);
        System.out.println("Joysticks: " + ergonomicController.joystickCount);
        System.out.println("Triggers: " + ergonomicController.triggerCount);
        System.out.println("Weight: " + ergonomicController.controllerWeight);
        System.out.println("Rechargeable: " + ergonomicController.isRechargeable);
        System.out.println("Device: " + ergonomicController.compatibleDevice);
        System.out.println("Warranty: " + ergonomicController.warrantyYears);
        System.out.println("Country: " + ergonomicController.originCountry);
        System.out.println("Price: " + ergonomicController.price);

        System.out.println("Travel Controller");
        System.out.println("Brand: " + travelController.controllerBrand);
        System.out.println("Connection: " + travelController.connectionType);
        System.out.println("Battery: " + travelController.batteryCapacity);
        System.out.println("Performance: " + travelController.performanceLevel);
        System.out.println("Vibration: " + travelController.hasVibration);
        System.out.println("Color: " + travelController.controllerColor);
        System.out.println("Buttons: " + travelController.numberOfButtons);
        System.out.println("Joysticks: " + travelController.joystickCount);
        System.out.println("Triggers: " + travelController.triggerCount);
        System.out.println("Weight: " + travelController.controllerWeight);
        System.out.println("Rechargeable: " + travelController.isRechargeable);
        System.out.println("Device: " + travelController.compatibleDevice);
        System.out.println("Warranty: " + travelController.warrantyYears);
        System.out.println("Country: " + travelController.originCountry);
        System.out.println("Price: " + travelController.price);

        System.out.println("Compact Controller");
        System.out.println("Brand: " + compactController.controllerBrand);
        System.out.println("Connection: " + compactController.connectionType);
        System.out.println("Battery: " + compactController.batteryCapacity);
        System.out.println("Performance: " + compactController.performanceLevel);
        System.out.println("Vibration: " + compactController.hasVibration);
        System.out.println("Color: " + compactController.controllerColor);
        System.out.println("Buttons: " + compactController.numberOfButtons);
        System.out.println("Joysticks: " + compactController.joystickCount);
        System.out.println("Triggers: " + compactController.triggerCount);
        System.out.println("Weight: " + compactController.controllerWeight);
        System.out.println("Rechargeable: " + compactController.isRechargeable);
        System.out.println("Device: " + compactController.compatibleDevice);
        System.out.println("Warranty: " + compactController.warrantyYears);
        System.out.println("Country: " + compactController.originCountry);
        System.out.println("Price: " + compactController.price);

        System.out.println("RGB Controller");
        System.out.println("Brand: " + rgbController.controllerBrand);
        System.out.println("Connection: " + rgbController.connectionType);
        System.out.println("Battery: " + rgbController.batteryCapacity);
        System.out.println("Performance: " + rgbController.performanceLevel);
        System.out.println("Vibration: " + rgbController.hasVibration);
        System.out.println("Color: " + rgbController.controllerColor);
        System.out.println("Buttons: " + rgbController.numberOfButtons);
        System.out.println("Joysticks: " + rgbController.joystickCount);
        System.out.println("Triggers: " + rgbController.triggerCount);
        System.out.println("Weight: " + rgbController.controllerWeight);
        System.out.println("Rechargeable: " + rgbController.isRechargeable);
        System.out.println("Device: " + rgbController.compatibleDevice);
        System.out.println("Warranty: " + rgbController.warrantyYears);
        System.out.println("Country: " + rgbController.originCountry);
        System.out.println("Price: " + rgbController.price);

        System.out.println("Pro Controller");
        System.out.println("Brand: " + proController.controllerBrand);
        System.out.println("Connection: " + proController.connectionType);
        System.out.println("Battery: " + proController.batteryCapacity);
        System.out.println("Performance: " + proController.performanceLevel);
        System.out.println("Vibration: " + proController.hasVibration);
        System.out.println("Color: " + proController.controllerColor);
        System.out.println("Buttons: " + proController.numberOfButtons);
        System.out.println("Joysticks: " + proController.joystickCount);
        System.out.println("Triggers: " + proController.triggerCount);
        System.out.println("Weight: " + proController.controllerWeight);
        System.out.println("Rechargeable: " + proController.isRechargeable);
        System.out.println("Device: " + proController.compatibleDevice);
        System.out.println("Warranty: " + proController.warrantyYears);
        System.out.println("Country: " + proController.originCountry);
        System.out.println("Price: " + proController.price);

        System.out.println("Advanced Controller");
        System.out.println("Brand: " + advancedController.controllerBrand);
        System.out.println("Connection: " + advancedController.connectionType);
        System.out.println("Battery: " + advancedController.batteryCapacity);
        System.out.println("Performance: " + advancedController.performanceLevel);
        System.out.println("Vibration: " + advancedController.hasVibration);
        System.out.println("Color: " + advancedController.controllerColor);
        System.out.println("Buttons: " + advancedController.numberOfButtons);
        System.out.println("Joysticks: " + advancedController.joystickCount);
        System.out.println("Triggers: " + advancedController.triggerCount);
        System.out.println("Weight: " + advancedController.controllerWeight);
        System.out.println("Rechargeable: " + advancedController.isRechargeable);
        System.out.println("Device: " + advancedController.compatibleDevice);
        System.out.println("Warranty: " + advancedController.warrantyYears);
        System.out.println("Country: " + advancedController.originCountry);
        System.out.println("Price: " + advancedController.price);
    }
}