class EthernetRunner{
    public static void main(String[] args) {

        Ethernet homeEthernet = new Ethernet();
        Ethernet officeEthernet = new Ethernet();
        Ethernet gamingEthernet = new Ethernet();
        Ethernet outdoorEthernet = new Ethernet();
        Ethernet indoorEthernet = new Ethernet();
        Ethernet highSpeedEthernet = new Ethernet();
        Ethernet compactEthernet = new Ethernet();
        Ethernet industrialEthernet = new Ethernet();
        Ethernet premiumEthernet = new Ethernet();
        Ethernet advancedEthernet = new Ethernet();

        homeEthernet.cableColor = "Blue";
        homeEthernet.cableLengthMeters = 10;
        homeEthernet.connectorCount = 2;
        homeEthernet.bandwidthMHz = 250;
        homeEthernet.cableWeight = 0.3;
        homeEthernet.isShielded = true;
        homeEthernet.usageType = "Home";
        homeEthernet.warrantyYears = 1;
        homeEthernet.originCountry = "India";
        homeEthernet.price = 500;

        System.out.println("Home Ethernet");
        System.out.println("Brand: " + homeEthernet.cableBrand);
        System.out.println("Category: " + homeEthernet.cableCategory);
        System.out.println("Speed: " + homeEthernet.speedMbps);
        System.out.println("Performance: " + homeEthernet.performanceLevel);
        System.out.println("Gigabit: " + homeEthernet.supportsGigabit);
        System.out.println("Color: " + homeEthernet.cableColor);
        System.out.println("Length: " + homeEthernet.cableLengthMeters);
        System.out.println("Connectors: " + homeEthernet.connectorCount);
        System.out.println("Bandwidth: " + homeEthernet.bandwidthMHz);
        System.out.println("Weight: " + homeEthernet.cableWeight);
        System.out.println("Shielded: " + homeEthernet.isShielded);
        System.out.println("Usage: " + homeEthernet.usageType);
        System.out.println("Warranty: " + homeEthernet.warrantyYears);
        System.out.println("Country: " + homeEthernet.originCountry);
        System.out.println("Price: " + homeEthernet.price);

        System.out.println("Office Ethernet");
        System.out.println("Brand: " + officeEthernet.cableBrand);
        System.out.println("Category: " + officeEthernet.cableCategory);
        System.out.println("Speed: " + officeEthernet.speedMbps);
        System.out.println("Performance: " + officeEthernet.performanceLevel);
        System.out.println("Gigabit: " + officeEthernet.supportsGigabit);
        System.out.println("Color: " + officeEthernet.cableColor);
        System.out.println("Length: " + officeEthernet.cableLengthMeters);
        System.out.println("Connectors: " + officeEthernet.connectorCount);
        System.out.println("Bandwidth: " + officeEthernet.bandwidthMHz);
        System.out.println("Weight: " + officeEthernet.cableWeight);
        System.out.println("Shielded: " + officeEthernet.isShielded);
        System.out.println("Usage: " + officeEthernet.usageType);
        System.out.println("Warranty: " + officeEthernet.warrantyYears);
        System.out.println("Country: " + officeEthernet.originCountry);
        System.out.println("Price: " + officeEthernet.price);

        System.out.println("Gaming Ethernet");
        System.out.println("Brand: " + gamingEthernet.cableBrand);
        System.out.println("Category: " + gamingEthernet.cableCategory);
        System.out.println("Speed: " + gamingEthernet.speedMbps);
        System.out.println("Performance: " + gamingEthernet.performanceLevel);
        System.out.println("Gigabit: " + gamingEthernet.supportsGigabit);
        System.out.println("Color: " + gamingEthernet.cableColor);
        System.out.println("Length: " + gamingEthernet.cableLengthMeters);
        System.out.println("Connectors: " + gamingEthernet.connectorCount);
        System.out.println("Bandwidth: " + gamingEthernet.bandwidthMHz);
        System.out.println("Weight: " + gamingEthernet.cableWeight);
        System.out.println("Shielded: " + gamingEthernet.isShielded);
        System.out.println("Usage: " + gamingEthernet.usageType);
        System.out.println("Warranty: " + gamingEthernet.warrantyYears);
        System.out.println("Country: " + gamingEthernet.originCountry);
        System.out.println("Price: " + gamingEthernet.price);

        System.out.println("Outdoor Ethernet");
        System.out.println("Brand: " + outdoorEthernet.cableBrand);
        System.out.println("Category: " + outdoorEthernet.cableCategory);
        System.out.println("Speed: " + outdoorEthernet.speedMbps);
        System.out.println("Performance: " + outdoorEthernet.performanceLevel);
        System.out.println("Gigabit: " + outdoorEthernet.supportsGigabit);
        System.out.println("Color: " + outdoorEthernet.cableColor);
        System.out.println("Length: " + outdoorEthernet.cableLengthMeters);
        System.out.println("Connectors: " + outdoorEthernet.connectorCount);
        System.out.println("Bandwidth: " + outdoorEthernet.bandwidthMHz);
        System.out.println("Weight: " + outdoorEthernet.cableWeight);
        System.out.println("Shielded: " + outdoorEthernet.isShielded);
        System.out.println("Usage: " + outdoorEthernet.usageType);
        System.out.println("Warranty: " + outdoorEthernet.warrantyYears);
        System.out.println("Country: " + outdoorEthernet.originCountry);
        System.out.println("Price: " + outdoorEthernet.price);

        System.out.println("Indoor Ethernet");
        System.out.println("Brand: " + indoorEthernet.cableBrand);
        System.out.println("Category: " + indoorEthernet.cableCategory);
        System.out.println("Speed: " + indoorEthernet.speedMbps);
        System.out.println("Performance: " + indoorEthernet.performanceLevel);
        System.out.println("Gigabit: " + indoorEthernet.supportsGigabit);
        System.out.println("Color: " + indoorEthernet.cableColor);
        System.out.println("Length: " + indoorEthernet.cableLengthMeters);
        System.out.println("Connectors: " + indoorEthernet.connectorCount);
        System.out.println("Bandwidth: " + indoorEthernet.bandwidthMHz);
        System.out.println("Weight: " + indoorEthernet.cableWeight);
        System.out.println("Shielded: " + indoorEthernet.isShielded);
        System.out.println("Usage: " + indoorEthernet.usageType);
        System.out.println("Warranty: " + indoorEthernet.warrantyYears);
        System.out.println("Country: " + indoorEthernet.originCountry);
        System.out.println("Price: " + indoorEthernet.price);

        System.out.println("High Speed Ethernet");
        System.out.println("Brand: " + highSpeedEthernet.cableBrand);
        System.out.println("Category: " + highSpeedEthernet.cableCategory);
        System.out.println("Speed: " + highSpeedEthernet.speedMbps);
        System.out.println("Performance: " + highSpeedEthernet.performanceLevel);
        System.out.println("Gigabit: " + highSpeedEthernet.supportsGigabit);
        System.out.println("Color: " + highSpeedEthernet.cableColor);
        System.out.println("Length: " + highSpeedEthernet.cableLengthMeters);
        System.out.println("Connectors: " + highSpeedEthernet.connectorCount);
        System.out.println("Bandwidth: " + highSpeedEthernet.bandwidthMHz);
        System.out.println("Weight: " + highSpeedEthernet.cableWeight);
        System.out.println("Shielded: " + highSpeedEthernet.isShielded);
        System.out.println("Usage: " + highSpeedEthernet.usageType);
        System.out.println("Warranty: " + highSpeedEthernet.warrantyYears);
        System.out.println("Country: " + highSpeedEthernet.originCountry);
        System.out.println("Price: " + highSpeedEthernet.price);

        System.out.println("Compact Ethernet");
        System.out.println("Brand: " + compactEthernet.cableBrand);
        System.out.println("Category: " + compactEthernet.cableCategory);
        System.out.println("Speed: " + compactEthernet.speedMbps);
        System.out.println("Performance: " + compactEthernet.performanceLevel);
        System.out.println("Gigabit: " + compactEthernet.supportsGigabit);
        System.out.println("Color: " + compactEthernet.cableColor);
        System.out.println("Length: " + compactEthernet.cableLengthMeters);
        System.out.println("Connectors: " + compactEthernet.connectorCount);
        System.out.println("Bandwidth: " + compactEthernet.bandwidthMHz);
        System.out.println("Weight: " + compactEthernet.cableWeight);
        System.out.println("Shielded: " + compactEthernet.isShielded);
        System.out.println("Usage: " + compactEthernet.usageType);
        System.out.println("Warranty: " + compactEthernet.warrantyYears);
        System.out.println("Country: " + compactEthernet.originCountry);
        System.out.println("Price: " + compactEthernet.price);

        System.out.println("Industrial Ethernet");
        System.out.println("Brand: " + industrialEthernet.cableBrand);
        System.out.println("Category: " + industrialEthernet.cableCategory);
        System.out.println("Speed: " + industrialEthernet.speedMbps);
        System.out.println("Performance: " + industrialEthernet.performanceLevel);
        System.out.println("Gigabit: " + industrialEthernet.supportsGigabit);
        System.out.println("Color: " + industrialEthernet.cableColor);
        System.out.println("Length: " + industrialEthernet.cableLengthMeters);
        System.out.println("Connectors: " + industrialEthernet.connectorCount);
        System.out.println("Bandwidth: " + industrialEthernet.bandwidthMHz);
        System.out.println("Weight: " + industrialEthernet.cableWeight);
        System.out.println("Shielded: " + industrialEthernet.isShielded);
        System.out.println("Usage: " + industrialEthernet.usageType);
        System.out.println("Warranty: " + industrialEthernet.warrantyYears);
        System.out.println("Country: " + industrialEthernet.originCountry);
        System.out.println("Price: " + industrialEthernet.price);

        System.out.println("Premium Ethernet");
        System.out.println("Brand: " + premiumEthernet.cableBrand);
        System.out.println("Category: " + premiumEthernet.cableCategory);
        System.out.println("Speed: " + premiumEthernet.speedMbps);
        System.out.println("Performance: " + premiumEthernet.performanceLevel);
        System.out.println("Gigabit: " + premiumEthernet.supportsGigabit);
        System.out.println("Color: " + premiumEthernet.cableColor);
        System.out.println("Length: " + premiumEthernet.cableLengthMeters);
        System.out.println("Connectors: " + premiumEthernet.connectorCount);
        System.out.println("Bandwidth: " + premiumEthernet.bandwidthMHz);
        System.out.println("Weight: " + premiumEthernet.cableWeight);
        System.out.println("Shielded: " + premiumEthernet.isShielded);
        System.out.println("Usage: " + premiumEthernet.usageType);
        System.out.println("Warranty: " + premiumEthernet.warrantyYears);
        System.out.println("Country: " + premiumEthernet.originCountry);
        System.out.println("Price: " + premiumEthernet.price);

        System.out.println("Advanced Ethernet");
        System.out.println("Brand: " + advancedEthernet.cableBrand);
        System.out.println("Category: " + advancedEthernet.cableCategory);
        System.out.println("Speed: " + advancedEthernet.speedMbps);
        System.out.println("Performance: " + advancedEthernet.performanceLevel);
        System.out.println("Gigabit: " + advancedEthernet.supportsGigabit);
        System.out.println("Color: " + advancedEthernet.cableColor);
        System.out.println("Length: " + advancedEthernet.cableLengthMeters);
        System.out.println("Connectors: " + advancedEthernet.connectorCount);
        System.out.println("Bandwidth: " + advancedEthernet.bandwidthMHz);
        System.out.println("Weight: " + advancedEthernet.cableWeight);
        System.out.println("Shielded: " + advancedEthernet.isShielded);
        System.out.println("Usage: " + advancedEthernet.usageType);
        System.out.println("Warranty: " + advancedEthernet.warrantyYears);
        System.out.println("Country: " + advancedEthernet.originCountry);
        System.out.println("Price: " + advancedEthernet.price);
    }
}