class FireRunner{
    public static void main(String[] args) {

        Fire campFire = new Fire();
        Fire forestFire = new Fire();
        Fire kitchenFire = new Fire();
        Fire electricalFire = new Fire();
        Fire gasFire = new Fire();
        Fire industrialFire = new Fire();
        Fire wildfire = new Fire();
        Fire controlledFire = new Fire();
        Fire accidentalFire = new Fire();
        Fire emergencyFire = new Fire();

        campFire.flameColor = "Orange";
        campFire.fireHeight = 5;
        campFire.fireWidth = 3;
        campFire.fireSpreadRadius = 2;
        campFire.fireDuration = 2.5;
        campFire.isControlled = true;
        campFire.locationType = "Outdoor";
        campFire.safetyRating = 8;
        campFire.originSource = "Wood";
        campFire.damageLevel = 2.0;

        System.out.println("Camp Fire");
        System.out.println("Type: " + campFire.fireType);
        System.out.println("Fuel: " + campFire.fuelType);
        System.out.println("Temperature: " + campFire.temperature);
        System.out.println("Intensity: " + campFire.intensityLevel);
        System.out.println("Smoke: " + campFire.producesSmoke);
        System.out.println("Flame Color: " + campFire.flameColor);
        System.out.println("Height: " + campFire.fireHeight);
        System.out.println("Width: " + campFire.fireWidth);
        System.out.println("Spread Radius: " + campFire.fireSpreadRadius);
        System.out.println("Duration: " + campFire.fireDuration);
        System.out.println("Controlled: " + campFire.isControlled);
        System.out.println("Location: " + campFire.locationType);
        System.out.println("Safety Rating: " + campFire.safetyRating);
        System.out.println("Origin: " + campFire.originSource);
        System.out.println("Damage Level: " + campFire.damageLevel);

        System.out.println("Forest Fire");
        System.out.println("Type: " + forestFire.fireType);
        System.out.println("Fuel: " + forestFire.fuelType);
        System.out.println("Temperature: " + forestFire.temperature);
        System.out.println("Intensity: " + forestFire.intensityLevel);
        System.out.println("Smoke: " + forestFire.producesSmoke);
        System.out.println("Flame Color: " + forestFire.flameColor);
        System.out.println("Height: " + forestFire.fireHeight);
        System.out.println("Width: " + forestFire.fireWidth);
        System.out.println("Spread Radius: " + forestFire.fireSpreadRadius);
        System.out.println("Duration: " + forestFire.fireDuration);
        System.out.println("Controlled: " + forestFire.isControlled);
        System.out.println("Location: " + forestFire.locationType);
        System.out.println("Safety Rating: " + forestFire.safetyRating);
        System.out.println("Origin: " + forestFire.originSource);
        System.out.println("Damage Level: " + forestFire.damageLevel);

        System.out.println("Kitchen Fire");
        System.out.println("Type: " + kitchenFire.fireType);
        System.out.println("Fuel: " + kitchenFire.fuelType);
        System.out.println("Temperature: " + kitchenFire.temperature);
        System.out.println("Intensity: " + kitchenFire.intensityLevel);
        System.out.println("Smoke: " + kitchenFire.producesSmoke);
        System.out.println("Flame Color: " + kitchenFire.flameColor);
        System.out.println("Height: " + kitchenFire.fireHeight);
        System.out.println("Width: " + kitchenFire.fireWidth);
        System.out.println("Spread Radius: " + kitchenFire.fireSpreadRadius);
        System.out.println("Duration: " + kitchenFire.fireDuration);
        System.out.println("Controlled: " + kitchenFire.isControlled);
        System.out.println("Location: " + kitchenFire.locationType);
        System.out.println("Safety Rating: " + kitchenFire.safetyRating);
        System.out.println("Origin: " + kitchenFire.originSource);
        System.out.println("Damage Level: " + kitchenFire.damageLevel);

        System.out.println("Electrical Fire");
        System.out.println("Type: " + electricalFire.fireType);
        System.out.println("Fuel: " + electricalFire.fuelType);
        System.out.println("Temperature: " + electricalFire.temperature);
        System.out.println("Intensity: " + electricalFire.intensityLevel);
        System.out.println("Smoke: " + electricalFire.producesSmoke);
        System.out.println("Flame Color: " + electricalFire.flameColor);
        System.out.println("Height: " + electricalFire.fireHeight);
        System.out.println("Width: " + electricalFire.fireWidth);
        System.out.println("Spread Radius: " + electricalFire.fireSpreadRadius);
        System.out.println("Duration: " + electricalFire.fireDuration);
        System.out.println("Controlled: " + electricalFire.isControlled);
        System.out.println("Location: " + electricalFire.locationType);
        System.out.println("Safety Rating: " + electricalFire.safetyRating);
        System.out.println("Origin: " + electricalFire.originSource);
        System.out.println("Damage Level: " + electricalFire.damageLevel);

        System.out.println("Gas Fire");
        System.out.println("Type: " + gasFire.fireType);
        System.out.println("Fuel: " + gasFire.fuelType);
        System.out.println("Temperature: " + gasFire.temperature);
        System.out.println("Intensity: " + gasFire.intensityLevel);
        System.out.println("Smoke: " + gasFire.producesSmoke);
        System.out.println("Flame Color: " + gasFire.flameColor);
        System.out.println("Height: " + gasFire.fireHeight);
        System.out.println("Width: " + gasFire.fireWidth);
        System.out.println("Spread Radius: " + gasFire.fireSpreadRadius);
        System.out.println("Duration: " + gasFire.fireDuration);
        System.out.println("Controlled: " + gasFire.isControlled);
        System.out.println("Location: " + gasFire.locationType);
        System.out.println("Safety Rating: " + gasFire.safetyRating);
        System.out.println("Origin: " + gasFire.originSource);
        System.out.println("Damage Level: " + gasFire.damageLevel);

        System.out.println("Industrial Fire");
        System.out.println("Type: " + industrialFire.fireType);
        System.out.println("Fuel: " + industrialFire.fuelType);
        System.out.println("Temperature: " + industrialFire.temperature);
        System.out.println("Intensity: " + industrialFire.intensityLevel);
        System.out.println("Smoke: " + industrialFire.producesSmoke);
        System.out.println("Flame Color: " + industrialFire.flameColor);
        System.out.println("Height: " + industrialFire.fireHeight);
        System.out.println("Width: " + industrialFire.fireWidth);
        System.out.println("Spread Radius: " + industrialFire.fireSpreadRadius);
        System.out.println("Duration: " + industrialFire.fireDuration);
        System.out.println("Controlled: " + industrialFire.isControlled);
        System.out.println("Location: " + industrialFire.locationType);
        System.out.println("Safety Rating: " + industrialFire.safetyRating);
        System.out.println("Origin: " + industrialFire.originSource);
        System.out.println("Damage Level: " + industrialFire.damageLevel);

        System.out.println("Wild Fire");
        System.out.println("Type: " + wildfire.fireType);
        System.out.println("Fuel: " + wildfire.fuelType);
        System.out.println("Temperature: " + wildfire.temperature);
        System.out.println("Intensity: " + wildfire.intensityLevel);
        System.out.println("Smoke: " + wildfire.producesSmoke);
        System.out.println("Flame Color: " + wildfire.flameColor);
        System.out.println("Height: " + wildfire.fireHeight);
        System.out.println("Width: " + wildfire.fireWidth);
        System.out.println("Spread Radius: " + wildfire.fireSpreadRadius);
        System.out.println("Duration: " + wildfire.fireDuration);
        System.out.println("Controlled: " + wildfire.isControlled);
        System.out.println("Location: " + wildfire.locationType);
        System.out.println("Safety Rating: " + wildfire.safetyRating);
        System.out.println("Origin: " + wildfire.originSource);
        System.out.println("Damage Level: " + wildfire.damageLevel);

        System.out.println("Controlled Fire");
        System.out.println("Type: " + controlledFire.fireType);
        System.out.println("Fuel: " + controlledFire.fuelType);
        System.out.println("Temperature: " + controlledFire.temperature);
        System.out.println("Intensity: " + controlledFire.intensityLevel);
        System.out.println("Smoke: " + controlledFire.producesSmoke);
        System.out.println("Flame Color: " + controlledFire.flameColor);
        System.out.println("Height: " + controlledFire.fireHeight);
        System.out.println("Width: " + controlledFire.fireWidth);
        System.out.println("Spread Radius: " + controlledFire.fireSpreadRadius);
        System.out.println("Duration: " + controlledFire.fireDuration);
        System.out.println("Controlled: " + controlledFire.isControlled);
        System.out.println("Location: " + controlledFire.locationType);
        System.out.println("Safety Rating: " + controlledFire.safetyRating);
        System.out.println("Origin: " + controlledFire.originSource);
        System.out.println("Damage Level: " + controlledFire.damageLevel);

        System.out.println("Accidental Fire");
        System.out.println("Type: " + accidentalFire.fireType);
        System.out.println("Fuel: " + accidentalFire.fuelType);
        System.out.println("Temperature: " + accidentalFire.temperature);
        System.out.println("Intensity: " + accidentalFire.intensityLevel);
        System.out.println("Smoke: " + accidentalFire.producesSmoke);
        System.out.println("Flame Color: " + accidentalFire.flameColor);
        System.out.println("Height: " + accidentalFire.fireHeight);
        System.out.println("Width: " + accidentalFire.fireWidth);
        System.out.println("Spread Radius: " + accidentalFire.fireSpreadRadius);
        System.out.println("Duration: " + accidentalFire.fireDuration);
        System.out.println("Controlled: " + accidentalFire.isControlled);
        System.out.println("Location: " + accidentalFire.locationType);
        System.out.println("Safety Rating: " + accidentalFire.safetyRating);
        System.out.println("Origin: " + accidentalFire.originSource);
        System.out.println("Damage Level: " + accidentalFire.damageLevel);

        System.out.println("Emergency Fire");
        System.out.println("Type: " + emergencyFire.fireType);
        System.out.println("Fuel: " + emergencyFire.fuelType);
        System.out.println("Temperature: " + emergencyFire.temperature);
        System.out.println("Intensity: " + emergencyFire.intensityLevel);
        System.out.println("Smoke: " + emergencyFire.producesSmoke);
        System.out.println("Flame Color: " + emergencyFire.flameColor);
        System.out.println("Height: " + emergencyFire.fireHeight);
        System.out.println("Width: " + emergencyFire.fireWidth);
        System.out.println("Spread Radius: " + emergencyFire.fireSpreadRadius);
        System.out.println("Duration: " + emergencyFire.fireDuration);
        System.out.println("Controlled: " + emergencyFire.isControlled);
        System.out.println("Location: " + emergencyFire.locationType);
        System.out.println("Safety Rating: " + emergencyFire.safetyRating);
        System.out.println("Origin: " + emergencyFire.originSource);
        System.out.println("Damage Level: " + emergencyFire.damageLevel);
    }
}