class GraphicCardRunner{
    public static void main(String[] args) {

        GraphicCard gamingCard = new GraphicCard();
        GraphicCard officeCard = new GraphicCard();
        GraphicCard budgetCard = new GraphicCard();
        GraphicCard highEndCard = new GraphicCard();
        GraphicCard miniCard = new GraphicCard();
        GraphicCard workstationCard = new GraphicCard();
        GraphicCard laptopCard = new GraphicCard();
        GraphicCard customCard = new GraphicCard();
        GraphicCard dualFanCard = new GraphicCard();
        GraphicCard tripleFanCard = new GraphicCard();

        gamingCard.modelName = "RTX 4090";
        gamingCard.coreClockSpeed = 2500;
        gamingCard.memoryBusWidth = 384;
        gamingCard.powerConsumption = 450;
        gamingCard.cardWeight = 2.5;
        gamingCard.isOverclocked = true;
        gamingCard.coolingSystem = "Triple Fan";
        gamingCard.warrantyYears = 3;
        gamingCard.originCountry = "China";
        gamingCard.price = 150000;

        System.out.println("Gaming Graphic Card");
        System.out.println("Chipset: " + gamingCard.chipsetType);
        System.out.println("Manufacturer: " + gamingCard.manufacturer);
        System.out.println("Temperature: " + gamingCard.heatTemperature);
        System.out.println("Performance: " + gamingCard.performanceLevel);
        System.out.println("Ray Tracing: " + gamingCard.supportsRayTracing);
        System.out.println("Model: " + gamingCard.modelName);
        System.out.println("Core Clock: " + gamingCard.coreClockSpeed);
        System.out.println("Bus Width: " + gamingCard.memoryBusWidth);
        System.out.println("Power: " + gamingCard.powerConsumption);
        System.out.println("Weight: " + gamingCard.cardWeight);
        System.out.println("Overclocked: " + gamingCard.isOverclocked);
        System.out.println("Cooling: " + gamingCard.coolingSystem);
        System.out.println("Warranty: " + gamingCard.warrantyYears);
        System.out.println("Country: " + gamingCard.originCountry);
        System.out.println("Price: " + gamingCard.price);

        System.out.println("Office Graphic Card");
        System.out.println("Chipset: " + officeCard.chipsetType);
        System.out.println("Manufacturer: " + officeCard.manufacturer);
        System.out.println("Temperature: " + officeCard.heatTemperature);
        System.out.println("Performance: " + officeCard.performanceLevel);
        System.out.println("Ray Tracing: " + officeCard.supportsRayTracing);
        System.out.println("Model: " + officeCard.modelName);
        System.out.println("Core Clock: " + officeCard.coreClockSpeed);
        System.out.println("Bus Width: " + officeCard.memoryBusWidth);
        System.out.println("Power: " + officeCard.powerConsumption);
        System.out.println("Weight: " + officeCard.cardWeight);
        System.out.println("Overclocked: " + officeCard.isOverclocked);
        System.out.println("Cooling: " + officeCard.coolingSystem);
        System.out.println("Warranty: " + officeCard.warrantyYears);
        System.out.println("Country: " + officeCard.originCountry);
        System.out.println("Price: " + officeCard.price);

        System.out.println("Budget Graphic Card");
        System.out.println("Chipset: " + budgetCard.chipsetType);
        System.out.println("Manufacturer: " + budgetCard.manufacturer);
        System.out.println("Temperature: " + budgetCard.heatTemperature);
        System.out.println("Performance: " + budgetCard.performanceLevel);
        System.out.println("Ray Tracing: " + budgetCard.supportsRayTracing);
        System.out.println("Model: " + budgetCard.modelName);
        System.out.println("Core Clock: " + budgetCard.coreClockSpeed);
        System.out.println("Bus Width: " + budgetCard.memoryBusWidth);
        System.out.println("Power: " + budgetCard.powerConsumption);
        System.out.println("Weight: " + budgetCard.cardWeight);
        System.out.println("Overclocked: " + budgetCard.isOverclocked);
        System.out.println("Cooling: " + budgetCard.coolingSystem);
        System.out.println("Warranty: " + budgetCard.warrantyYears);
        System.out.println("Country: " + budgetCard.originCountry);
        System.out.println("Price: " + budgetCard.price);

        System.out.println("HighEnd Graphic Card");
        System.out.println("Chipset: " + highEndCard.chipsetType);
        System.out.println("Manufacturer: " + highEndCard.manufacturer);
        System.out.println("Temperature: " + highEndCard.heatTemperature);
        System.out.println("Performance: " + highEndCard.performanceLevel);
        System.out.println("Ray Tracing: " + highEndCard.supportsRayTracing);
        System.out.println("Model: " + highEndCard.modelName);
        System.out.println("Core Clock: " + highEndCard.coreClockSpeed);
        System.out.println("Bus Width: " + highEndCard.memoryBusWidth);
        System.out.println("Power: " + highEndCard.powerConsumption);
        System.out.println("Weight: " + highEndCard.cardWeight);
        System.out.println("Overclocked: " + highEndCard.isOverclocked);
        System.out.println("Cooling: " + highEndCard.coolingSystem);
        System.out.println("Warranty: " + highEndCard.warrantyYears);
        System.out.println("Country: " + highEndCard.originCountry);
        System.out.println("Price: " + highEndCard.price);

        System.out.println("Mini Graphic Card");
        System.out.println("Chipset: " + miniCard.chipsetType);
        System.out.println("Manufacturer: " + miniCard.manufacturer);
        System.out.println("Temperature: " + miniCard.heatTemperature);
        System.out.println("Performance: " + miniCard.performanceLevel);
        System.out.println("Ray Tracing: " + miniCard.supportsRayTracing);
        System.out.println("Model: " + miniCard.modelName);
        System.out.println("Core Clock: " + miniCard.coreClockSpeed);
        System.out.println("Bus Width: " + miniCard.memoryBusWidth);
        System.out.println("Power: " + miniCard.powerConsumption);
        System.out.println("Weight: " + miniCard.cardWeight);
        System.out.println("Overclocked: " + miniCard.isOverclocked);
        System.out.println("Cooling: " + miniCard.coolingSystem);
        System.out.println("Warranty: " + miniCard.warrantyYears);
        System.out.println("Country: " + miniCard.originCountry);
        System.out.println("Price: " + miniCard.price);

        System.out.println("Workstation Graphic Card");
        System.out.println("Chipset: " + workstationCard.chipsetType);
        System.out.println("Manufacturer: " + workstationCard.manufacturer);
        System.out.println("Temperature: " + workstationCard.heatTemperature);
        System.out.println("Performance: " + workstationCard.performanceLevel);
        System.out.println("Ray Tracing: " + workstationCard.supportsRayTracing);
        System.out.println("Model: " + workstationCard.modelName);
        System.out.println("Core Clock: " + workstationCard.coreClockSpeed);
        System.out.println("Bus Width: " + workstationCard.memoryBusWidth);
        System.out.println("Power: " + workstationCard.powerConsumption);
        System.out.println("Weight: " + workstationCard.cardWeight);
        System.out.println("Overclocked: " + workstationCard.isOverclocked);
        System.out.println("Cooling: " + workstationCard.coolingSystem);
        System.out.println("Warranty: " + workstationCard.warrantyYears);
        System.out.println("Country: " + workstationCard.originCountry);
        System.out.println("Price: " + workstationCard.price);

        System.out.println("Laptop Graphic Card");
        System.out.println("Chipset: " + laptopCard.chipsetType);
        System.out.println("Manufacturer: " + laptopCard.manufacturer);
        System.out.println("Temperature: " + laptopCard.heatTemperature);
        System.out.println("Performance: " + laptopCard.performanceLevel);
        System.out.println("Ray Tracing: " + laptopCard.supportsRayTracing);
        System.out.println("Model: " + laptopCard.modelName);
        System.out.println("Core Clock: " + laptopCard.coreClockSpeed);
        System.out.println("Bus Width: " + laptopCard.memoryBusWidth);
        System.out.println("Power: " + laptopCard.powerConsumption);
        System.out.println("Weight: " + laptopCard.cardWeight);
        System.out.println("Overclocked: " + laptopCard.isOverclocked);
        System.out.println("Cooling: " + laptopCard.coolingSystem);
        System.out.println("Warranty: " + laptopCard.warrantyYears);
        System.out.println("Country: " + laptopCard.originCountry);
        System.out.println("Price: " + laptopCard.price);

        System.out.println("Custom Graphic Card");
        System.out.println("Chipset: " + customCard.chipsetType);
        System.out.println("Manufacturer: " + customCard.manufacturer);
        System.out.println("Temperature: " + customCard.heatTemperature);
        System.out.println("Performance: " + customCard.performanceLevel);
        System.out.println("Ray Tracing: " + customCard.supportsRayTracing);
        System.out.println("Model: " + customCard.modelName);
        System.out.println("Core Clock: " + customCard.coreClockSpeed);
        System.out.println("Bus Width: " + customCard.memoryBusWidth);
        System.out.println("Power: " + customCard.powerConsumption);
        System.out.println("Weight: " + customCard.cardWeight);
        System.out.println("Overclocked: " + customCard.isOverclocked);
        System.out.println("Cooling: " + customCard.coolingSystem);
        System.out.println("Warranty: " + customCard.warrantyYears);
        System.out.println("Country: " + customCard.originCountry);
        System.out.println("Price: " + customCard.price);

        System.out.println("DualFan Graphic Card");
        System.out.println("Chipset: " + dualFanCard.chipsetType);
        System.out.println("Manufacturer: " + dualFanCard.manufacturer);
        System.out.println("Temperature: " + dualFanCard.heatTemperature);
        System.out.println("Performance: " + dualFanCard.performanceLevel);
        System.out.println("Ray Tracing: " + dualFanCard.supportsRayTracing);
        System.out.println("Model: " + dualFanCard.modelName);
        System.out.println("Core Clock: " + dualFanCard.coreClockSpeed);
        System.out.println("Bus Width: " + dualFanCard.memoryBusWidth);
        System.out.println("Power: " + dualFanCard.powerConsumption);
        System.out.println("Weight: " + dualFanCard.cardWeight);
        System.out.println("Overclocked: " + dualFanCard.isOverclocked);
        System.out.println("Cooling: " + dualFanCard.coolingSystem);
        System.out.println("Warranty: " + dualFanCard.warrantyYears);
        System.out.println("Country: " + dualFanCard.originCountry);
        System.out.println("Price: " + dualFanCard.price);

        System.out.println("TripleFan Graphic Card");
        System.out.println("Chipset: " + tripleFanCard.chipsetType);
        System.out.println("Manufacturer: " + tripleFanCard.manufacturer);
        System.out.println("Temperature: " + tripleFanCard.heatTemperature);
        System.out.println("Performance: " + tripleFanCard.performanceLevel);
        System.out.println("Ray Tracing: " + tripleFanCard.supportsRayTracing);
        System.out.println("Model: " + tripleFanCard.modelName);
        System.out.println("Core Clock: " + tripleFanCard.coreClockSpeed);
        System.out.println("Bus Width: " + tripleFanCard.memoryBusWidth);
        System.out.println("Power: " + tripleFanCard.powerConsumption);
        System.out.println("Weight: " + tripleFanCard.cardWeight);
        System.out.println("Overclocked: " + tripleFanCard.isOverclocked);
        System.out.println("Cooling: " + tripleFanCard.coolingSystem);
        System.out.println("Warranty: " + tripleFanCard.warrantyYears);
        System.out.println("Country: " + tripleFanCard.originCountry);
        System.out.println("Price: " + tripleFanCard.price);
    }
}