class LampRunner{
    public static void main(String[] args){

        Lamp studyLamp = new Lamp();
        Lamp tableLamp = new Lamp();
        Lamp deskLamp = new Lamp();
        Lamp ledLamp = new Lamp();
        Lamp nightLamp = new Lamp();
        Lamp emergencyLamp = new Lamp();
        Lamp readingLamp = new Lamp();
        Lamp smartLamp = new Lamp();
        Lamp wallLamp = new Lamp();
        Lamp floorLamp = new Lamp();

        studyLamp.lightColor = "White";
        studyLamp.lampHeight = 30;
        studyLamp.lampWidth = 12;
        studyLamp.lampDepth = 10;
        studyLamp.lampWeight = 1.5;
        studyLamp.isPortable = true;
        studyLamp.lampUsageType = "Study";
        studyLamp.warrantyInYears = 2;
        studyLamp.manufacturedCountry = "India";
        studyLamp.discountPercentage = 5;

        System.out.println("Study Lamp");
        System.out.println("Brand: " + studyLamp.brand);
        System.out.println("Material: " + studyLamp.material);
        System.out.println("Power: " + studyLamp.powerInWatts);
        System.out.println("Price: " + studyLamp.price);
        System.out.println("Battery Backup: " + studyLamp.hasBatteryBackup);
        System.out.println("Color: " + studyLamp.lightColor);
        System.out.println("Height: " + studyLamp.lampHeight);
        System.out.println("Width: " + studyLamp.lampWidth);
        System.out.println("Depth: " + studyLamp.lampDepth);
        System.out.println("Weight: " + studyLamp.lampWeight);
        System.out.println("Portable: " + studyLamp.isPortable);
        System.out.println("Usage Type: " + studyLamp.lampUsageType);
        System.out.println("Warranty: " + studyLamp.warrantyInYears);
        System.out.println("Country: " + studyLamp.manufacturedCountry);
        System.out.println("Discount: " + studyLamp.discountPercentage);

        System.out.println("Table Lamp");
        System.out.println("Brand: " + tableLamp.brand);
        System.out.println("Material: " + tableLamp.material);
        System.out.println("Power: " + tableLamp.powerInWatts);
        System.out.println("Price: " + tableLamp.price);
        System.out.println("Battery Backup: " + tableLamp.hasBatteryBackup);
        System.out.println("Color: " + tableLamp.lightColor);
        System.out.println("Height: " + tableLamp.lampHeight);
        System.out.println("Width: " + tableLamp.lampWidth);
        System.out.println("Depth: " + tableLamp.lampDepth);
        System.out.println("Weight: " + tableLamp.lampWeight);
        System.out.println("Portable: " + tableLamp.isPortable);
        System.out.println("Usage Type: " + tableLamp.lampUsageType);
        System.out.println("Warranty: " + tableLamp.warrantyInYears);
        System.out.println("Country: " + tableLamp.manufacturedCountry);
        System.out.println("Discount: " + tableLamp.discountPercentage);

        System.out.println("Desk Lamp");
        System.out.println("Brand: " + deskLamp.brand);
        System.out.println("Material: " + deskLamp.material);
        System.out.println("Power: " + deskLamp.powerInWatts);
        System.out.println("Price: " + deskLamp.price);
        System.out.println("Battery Backup: " + deskLamp.hasBatteryBackup);
        System.out.println("Color: " + deskLamp.lightColor);
        System.out.println("Height: " + deskLamp.lampHeight);
        System.out.println("Width: " + deskLamp.lampWidth);
        System.out.println("Depth: " + deskLamp.lampDepth);
        System.out.println("Weight: " + deskLamp.lampWeight);
        System.out.println("Portable: " + deskLamp.isPortable);
        System.out.println("Usage Type: " + deskLamp.lampUsageType);
        System.out.println("Warranty: " + deskLamp.warrantyInYears);
        System.out.println("Country: " + deskLamp.manufacturedCountry);
        System.out.println("Discount: " + deskLamp.discountPercentage);

        System.out.println("LED Lamp");
        System.out.println("Brand: " + ledLamp.brand);
        System.out.println("Material: " + ledLamp.material);
        System.out.println("Power: " + ledLamp.powerInWatts);
        System.out.println("Price: " + ledLamp.price);
        System.out.println("Battery Backup: " + ledLamp.hasBatteryBackup);
        System.out.println("Color: " + ledLamp.lightColor);
        System.out.println("Height: " + ledLamp.lampHeight);
        System.out.println("Width: " + ledLamp.lampWidth);
        System.out.println("Depth: " + ledLamp.lampDepth);
        System.out.println("Weight: " + ledLamp.lampWeight);
        System.out.println("Portable: " + ledLamp.isPortable);
        System.out.println("Usage Type: " + ledLamp.lampUsageType);
        System.out.println("Warranty: " + ledLamp.warrantyInYears);
        System.out.println("Country: " + ledLamp.manufacturedCountry);
        System.out.println("Discount: " + ledLamp.discountPercentage);

        System.out.println("Night Lamp");
        System.out.println("Brand: " + nightLamp.brand);
        System.out.println("Material: " + nightLamp.material);
        System.out.println("Power: " + nightLamp.powerInWatts);
        System.out.println("Price: " + nightLamp.price);
        System.out.println("Battery Backup: " + nightLamp.hasBatteryBackup);
        System.out.println("Color: " + nightLamp.lightColor);
        System.out.println("Height: " + nightLamp.lampHeight);
        System.out.println("Width: " + nightLamp.lampWidth);
        System.out.println("Depth: " + nightLamp.lampDepth);
        System.out.println("Weight: " + nightLamp.lampWeight);
        System.out.println("Portable: " + nightLamp.isPortable);
        System.out.println("Usage Type: " + nightLamp.lampUsageType);
        System.out.println("Warranty: " + nightLamp.warrantyInYears);
        System.out.println("Country: " + nightLamp.manufacturedCountry);
        System.out.println("Discount: " + nightLamp.discountPercentage);

        System.out.println("Emergency Lamp");
        System.out.println("Brand: " + emergencyLamp.brand);
        System.out.println("Material: " + emergencyLamp.material);
        System.out.println("Power: " + emergencyLamp.powerInWatts);
        System.out.println("Price: " + emergencyLamp.price);
        System.out.println("Battery Backup: " + emergencyLamp.hasBatteryBackup);
        System.out.println("Color: " + emergencyLamp.lightColor);
        System.out.println("Height: " + emergencyLamp.lampHeight);
        System.out.println("Width: " + emergencyLamp.lampWidth);
        System.out.println("Depth: " + emergencyLamp.lampDepth);
        System.out.println("Weight: " + emergencyLamp.lampWeight);
        System.out.println("Portable: " + emergencyLamp.isPortable);
        System.out.println("Usage Type: " + emergencyLamp.lampUsageType);
        System.out.println("Warranty: " + emergencyLamp.warrantyInYears);
        System.out.println("Country: " + emergencyLamp.manufacturedCountry);
        System.out.println("Discount: " + emergencyLamp.discountPercentage);

        System.out.println("Reading Lamp");
        System.out.println("Brand: " + readingLamp.brand);
        System.out.println("Material: " + readingLamp.material);
        System.out.println("Power: " + readingLamp.powerInWatts);
        System.out.println("Price: " + readingLamp.price);
        System.out.println("Battery Backup: " + readingLamp.hasBatteryBackup);
        System.out.println("Color: " + readingLamp.lightColor);
        System.out.println("Height: " + readingLamp.lampHeight);
        System.out.println("Width: " + readingLamp.lampWidth);
        System.out.println("Depth: " + readingLamp.lampDepth);
        System.out.println("Weight: " + readingLamp.lampWeight);
        System.out.println("Portable: " + readingLamp.isPortable);
        System.out.println("Usage Type: " + readingLamp.lampUsageType);
        System.out.println("Warranty: " + readingLamp.warrantyInYears);
        System.out.println("Country: " + readingLamp.manufacturedCountry);
        System.out.println("Discount: " + readingLamp.discountPercentage);

        System.out.println("Smart Lamp");
        System.out.println("Brand: " + smartLamp.brand);
        System.out.println("Material: " + smartLamp.material);
        System.out.println("Power: " + smartLamp.powerInWatts);
        System.out.println("Price: " + smartLamp.price);
        System.out.println("Battery Backup: " + smartLamp.hasBatteryBackup);
        System.out.println("Color: " + smartLamp.lightColor);
        System.out.println("Height: " + smartLamp.lampHeight);
        System.out.println("Width: " + smartLamp.lampWidth);
        System.out.println("Depth: " + smartLamp.lampDepth);
        System.out.println("Weight: " + smartLamp.lampWeight);
        System.out.println("Portable: " + smartLamp.isPortable);
        System.out.println("Usage Type: " + smartLamp.lampUsageType);
        System.out.println("Warranty: " + smartLamp.warrantyInYears);
        System.out.println("Country: " + smartLamp.manufacturedCountry);
        System.out.println("Discount: " + smartLamp.discountPercentage);

        System.out.println("Wall Lamp");
        System.out.println("Brand: " + wallLamp.brand);
        System.out.println("Material: " + wallLamp.material);
        System.out.println("Power: " + wallLamp.powerInWatts);
        System.out.println("Price: " + wallLamp.price);
        System.out.println("Battery Backup: " + wallLamp.hasBatteryBackup);
        System.out.println("Color: " + wallLamp.lightColor);
        System.out.println("Height: " + wallLamp.lampHeight);
        System.out.println("Width: " + wallLamp.lampWidth);
        System.out.println("Depth: " + wallLamp.lampDepth);
        System.out.println("Weight: " + wallLamp.lampWeight);
        System.out.println("Portable: " + wallLamp.isPortable);
        System.out.println("Usage Type: " + wallLamp.lampUsageType);
        System.out.println("Warranty: " + wallLamp.warrantyInYears);
        System.out.println("Country: " + wallLamp.manufacturedCountry);
        System.out.println("Discount: " + wallLamp.discountPercentage);

        System.out.println("Floor Lamp");
        System.out.println("Brand: " + floorLamp.brand);
        System.out.println("Material: " + floorLamp.material);
        System.out.println("Power: " + floorLamp.powerInWatts);
        System.out.println("Price: " + floorLamp.price);
        System.out.println("Battery Backup: " + floorLamp.hasBatteryBackup);
        System.out.println("Color: " + floorLamp.lightColor);
        System.out.println("Height: " + floorLamp.lampHeight);
        System.out.println("Width: " + floorLamp.lampWidth);
        System.out.println("Depth: " + floorLamp.lampDepth);
        System.out.println("Weight: " + floorLamp.lampWeight);
        System.out.println("Portable: " + floorLamp.isPortable);
        System.out.println("Usage Type: " + floorLamp.lampUsageType);
        System.out.println("Warranty: " + floorLamp.warrantyInYears);
        System.out.println("Country: " + floorLamp.manufacturedCountry);
        System.out.println("Discount: " + floorLamp.discountPercentage);
    }
}