class MouseRunner{
    public static void main(String[] args){

        Mouse officeMouse = new Mouse();
        Mouse gamingMouse = new Mouse();
        Mouse wirelessMouse = new Mouse();
        Mouse bluetoothMouse = new Mouse();
        Mouse ergonomicMouse = new Mouse();
        Mouse travelMouse = new Mouse();
        Mouse compactMouse = new Mouse();
        Mouse rgbMouse = new Mouse();
        Mouse silentMouse = new Mouse();
        Mouse professionalMouse = new Mouse();

        officeMouse.mouseColor = "Black";
        officeMouse.mouseLength = 12;
        officeMouse.mouseWidth = 6;
        officeMouse.mouseHeight = 4;
        officeMouse.mouseWeight = 0.2;
        officeMouse.isRechargeable = true;
        officeMouse.usageType = "Office";
        officeMouse.warrantyInYears = 2;
        officeMouse.manufacturedCountry = "India";
        officeMouse.discountPercentage = 5;

        System.out.println("Office Mouse");
        System.out.println("Brand: " + officeMouse.brand);
        System.out.println("Connection: " + officeMouse.connectionType);
        System.out.println("DPI: " + officeMouse.dpi);
        System.out.println("Price: " + officeMouse.price);
        System.out.println("Scroll Wheel: " + officeMouse.hasScrollWheel);
        System.out.println("Color: " + officeMouse.mouseColor);
        System.out.println("Length: " + officeMouse.mouseLength);
        System.out.println("Width: " + officeMouse.mouseWidth);
        System.out.println("Height: " + officeMouse.mouseHeight);
        System.out.println("Weight: " + officeMouse.mouseWeight);
        System.out.println("Rechargeable: " + officeMouse.isRechargeable);
        System.out.println("Usage Type: " + officeMouse.usageType);
        System.out.println("Warranty: " + officeMouse.warrantyInYears);
        System.out.println("Country: " + officeMouse.manufacturedCountry);
        System.out.println("Discount: " + officeMouse.discountPercentage);

        System.out.println("Gaming Mouse");
        System.out.println("Brand: " + gamingMouse.brand);
        System.out.println("Connection: " + gamingMouse.connectionType);
        System.out.println("DPI: " + gamingMouse.dpi);
        System.out.println("Price: " + gamingMouse.price);
        System.out.println("Scroll Wheel: " + gamingMouse.hasScrollWheel);
        System.out.println("Color: " + gamingMouse.mouseColor);
        System.out.println("Length: " + gamingMouse.mouseLength);
        System.out.println("Width: " + gamingMouse.mouseWidth);
        System.out.println("Height: " + gamingMouse.mouseHeight);
        System.out.println("Weight: " + gamingMouse.mouseWeight);
        System.out.println("Rechargeable: " + gamingMouse.isRechargeable);
        System.out.println("Usage Type: " + gamingMouse.usageType);
        System.out.println("Warranty: " + gamingMouse.warrantyInYears);
        System.out.println("Country: " + gamingMouse.manufacturedCountry);
        System.out.println("Discount: " + gamingMouse.discountPercentage);

        System.out.println("Wireless Mouse");
        System.out.println("Brand: " + wirelessMouse.brand);
        System.out.println("Connection: " + wirelessMouse.connectionType);
        System.out.println("DPI: " + wirelessMouse.dpi);
        System.out.println("Price: " + wirelessMouse.price);
        System.out.println("Scroll Wheel: " + wirelessMouse.hasScrollWheel);
        System.out.println("Color: " + wirelessMouse.mouseColor);
        System.out.println("Length: " + wirelessMouse.mouseLength);
        System.out.println("Width: " + wirelessMouse.mouseWidth);
        System.out.println("Height: " + wirelessMouse.mouseHeight);
        System.out.println("Weight: " + wirelessMouse.mouseWeight);
        System.out.println("Rechargeable: " + wirelessMouse.isRechargeable);
        System.out.println("Usage Type: " + wirelessMouse.usageType);
        System.out.println("Warranty: " + wirelessMouse.warrantyInYears);
        System.out.println("Country: " + wirelessMouse.manufacturedCountry);
        System.out.println("Discount: " + wirelessMouse.discountPercentage);

        System.out.println("Bluetooth Mouse");
        System.out.println("Brand: " + bluetoothMouse.brand);
        System.out.println("Connection: " + bluetoothMouse.connectionType);
        System.out.println("DPI: " + bluetoothMouse.dpi);
        System.out.println("Price: " + bluetoothMouse.price);
        System.out.println("Scroll Wheel: " + bluetoothMouse.hasScrollWheel);
        System.out.println("Color: " + bluetoothMouse.mouseColor);
        System.out.println("Length: " + bluetoothMouse.mouseLength);
        System.out.println("Width: " + bluetoothMouse.mouseWidth);
        System.out.println("Height: " + bluetoothMouse.mouseHeight);
        System.out.println("Weight: " + bluetoothMouse.mouseWeight);
        System.out.println("Rechargeable: " + bluetoothMouse.isRechargeable);
        System.out.println("Usage Type: " + bluetoothMouse.usageType);
        System.out.println("Warranty: " + bluetoothMouse.warrantyInYears);
        System.out.println("Country: " + bluetoothMouse.manufacturedCountry);
        System.out.println("Discount: " + bluetoothMouse.discountPercentage);

        System.out.println("Ergonomic Mouse");
        System.out.println("Brand: " + ergonomicMouse.brand);
        System.out.println("Connection: " + ergonomicMouse.connectionType);
        System.out.println("DPI: " + ergonomicMouse.dpi);
        System.out.println("Price: " + ergonomicMouse.price);
        System.out.println("Scroll Wheel: " + ergonomicMouse.hasScrollWheel);
        System.out.println("Color: " + ergonomicMouse.mouseColor);
        System.out.println("Length: " + ergonomicMouse.mouseLength);
        System.out.println("Width: " + ergonomicMouse.mouseWidth);
        System.out.println("Height: " + ergonomicMouse.mouseHeight);
        System.out.println("Weight: " + ergonomicMouse.mouseWeight);
        System.out.println("Rechargeable: " + ergonomicMouse.isRechargeable);
        System.out.println("Usage Type: " + ergonomicMouse.usageType);
        System.out.println("Warranty: " + ergonomicMouse.warrantyInYears);
        System.out.println("Country: " + ergonomicMouse.manufacturedCountry);
        System.out.println("Discount: " + ergonomicMouse.discountPercentage);

        System.out.println("Travel Mouse");
        System.out.println("Brand: " + travelMouse.brand);
        System.out.println("Connection: " + travelMouse.connectionType);
        System.out.println("DPI: " + travelMouse.dpi);
        System.out.println("Price: " + travelMouse.price);
        System.out.println("Scroll Wheel: " + travelMouse.hasScrollWheel);
        System.out.println("Color: " + travelMouse.mouseColor);
        System.out.println("Length: " + travelMouse.mouseLength);
        System.out.println("Width: " + travelMouse.mouseWidth);
        System.out.println("Height: " + travelMouse.mouseHeight);
        System.out.println("Weight: " + travelMouse.mouseWeight);
        System.out.println("Rechargeable: " + travelMouse.isRechargeable);
        System.out.println("Usage Type: " + travelMouse.usageType);
        System.out.println("Warranty: " + travelMouse.warrantyInYears);
        System.out.println("Country: " + travelMouse.manufacturedCountry);
        System.out.println("Discount: " + travelMouse.discountPercentage);

        System.out.println("Compact Mouse");
        System.out.println("Brand: " + compactMouse.brand);
        System.out.println("Connection: " + compactMouse.connectionType);
        System.out.println("DPI: " + compactMouse.dpi);
        System.out.println("Price: " + compactMouse.price);
        System.out.println("Scroll Wheel: " + compactMouse.hasScrollWheel);
        System.out.println("Color: " + compactMouse.mouseColor);
        System.out.println("Length: " + compactMouse.mouseLength);
        System.out.println("Width: " + compactMouse.mouseWidth);
        System.out.println("Height: " + compactMouse.mouseHeight);
        System.out.println("Weight: " + compactMouse.mouseWeight);
        System.out.println("Rechargeable: " + compactMouse.isRechargeable);
        System.out.println("Usage Type: " + compactMouse.usageType);
        System.out.println("Warranty: " + compactMouse.warrantyInYears);
        System.out.println("Country: " + compactMouse.manufacturedCountry);
        System.out.println("Discount: " + compactMouse.discountPercentage);

        System.out.println("RGB Mouse");
        System.out.println("Brand: " + rgbMouse.brand);
        System.out.println("Connection: " + rgbMouse.connectionType);
        System.out.println("DPI: " + rgbMouse.dpi);
        System.out.println("Price: " + rgbMouse.price);
        System.out.println("Scroll Wheel: " + rgbMouse.hasScrollWheel);
        System.out.println("Color: " + rgbMouse.mouseColor);
        System.out.println("Length: " + rgbMouse.mouseLength);
        System.out.println("Width: " + rgbMouse.mouseWidth);
        System.out.println("Height: " + rgbMouse.mouseHeight);
        System.out.println("Weight: " + rgbMouse.mouseWeight);
        System.out.println("Rechargeable: " + rgbMouse.isRechargeable);
        System.out.println("Usage Type: " + rgbMouse.usageType);
        System.out.println("Warranty: " + rgbMouse.warrantyInYears);
        System.out.println("Country: " + rgbMouse.manufacturedCountry);
        System.out.println("Discount: " + rgbMouse.discountPercentage);

        System.out.println("Silent Mouse");
        System.out.println("Brand: " + silentMouse.brand);
        System.out.println("Connection: " + silentMouse.connectionType);
        System.out.println("DPI: " + silentMouse.dpi);
        System.out.println("Price: " + silentMouse.price);
        System.out.println("Scroll Wheel: " + silentMouse.hasScrollWheel);
        System.out.println("Color: " + silentMouse.mouseColor);
        System.out.println("Length: " + silentMouse.mouseLength);
        System.out.println("Width: " + silentMouse.mouseWidth);
        System.out.println("Height: " + silentMouse.mouseHeight);
        System.out.println("Weight: " + silentMouse.mouseWeight);
        System.out.println("Rechargeable: " + silentMouse.isRechargeable);
        System.out.println("Usage Type: " + silentMouse.usageType);
        System.out.println("Warranty: " + silentMouse.warrantyInYears);
        System.out.println("Country: " + silentMouse.manufacturedCountry);
        System.out.println("Discount: " + silentMouse.discountPercentage);

        System.out.println("Professional Mouse");
        System.out.println("Brand: " + professionalMouse.brand);
        System.out.println("Connection: " + professionalMouse.connectionType);
        System.out.println("DPI: " + professionalMouse.dpi);
        System.out.println("Price: " + professionalMouse.price);
        System.out.println("Scroll Wheel: " + professionalMouse.hasScrollWheel);
        System.out.println("Color: " + professionalMouse.mouseColor);
        System.out.println("Length: " + professionalMouse.mouseLength);
        System.out.println("Width: " + professionalMouse.mouseWidth);
        System.out.println("Height: " + professionalMouse.mouseHeight);
        System.out.println("Weight: " + professionalMouse.mouseWeight);
        System.out.println("Rechargeable: " + professionalMouse.isRechargeable);
        System.out.println("Usage Type: " + professionalMouse.usageType);
        System.out.println("Warranty: " + professionalMouse.warrantyInYears);
        System.out.println("Country: " + professionalMouse.manufacturedCountry);
        System.out.println("Discount: " + professionalMouse.discountPercentage);
    }
}