class ProjectorRunner{
    public static void main(String[] args){

        Projector homeProjector = new Projector();
        Projector officeProjector = new Projector();
        Projector miniProjector = new Projector();
        Projector smartProjector = new Projector();
        Projector laserProjector = new Projector();
        Projector portableProjector = new Projector();
        Projector classroomProjector = new Projector();
        Projector cinemaProjector = new Projector();
        Projector gamingProjector = new Projector();
        Projector ledProjector = new Projector();

        homeProjector.projectorColor = "White";
        homeProjector.resolutionWidth = 1920;
        homeProjector.resolutionHeight = 1080;
        homeProjector.contrastRatio = 2000;
        homeProjector.projectorWeight = 2.5;
        homeProjector.isPortable = true;
        homeProjector.usageType = "Home";
        homeProjector.warrantyYears = 2;
        homeProjector.originCountry = "Japan";
        homeProjector.price = 35000;

        System.out.println("Home Projector");
        System.out.println("Brand: " + homeProjector.projectorBrand);
        System.out.println("Technology: " + homeProjector.projectionTechnology);
        System.out.println("Brightness: " + homeProjector.brightnessLumens);
        System.out.println("Quality: " + homeProjector.displayQuality);
        System.out.println("Full HD: " + homeProjector.supportsFullHD);
        System.out.println("Color: " + homeProjector.projectorColor);
        System.out.println("Width: " + homeProjector.resolutionWidth);
        System.out.println("Height: " + homeProjector.resolutionHeight);
        System.out.println("Contrast: " + homeProjector.contrastRatio);
        System.out.println("Weight: " + homeProjector.projectorWeight);
        System.out.println("Portable: " + homeProjector.isPortable);
        System.out.println("Usage: " + homeProjector.usageType);
        System.out.println("Warranty: " + homeProjector.warrantyYears);
        System.out.println("Country: " + homeProjector.originCountry);
        System.out.println("Price: " + homeProjector.price);

        System.out.println("Office Projector");
        System.out.println("Brand: " + officeProjector.projectorBrand);
        System.out.println("Technology: " + officeProjector.projectionTechnology);
        System.out.println("Brightness: " + officeProjector.brightnessLumens);
        System.out.println("Quality: " + officeProjector.displayQuality);
        System.out.println("Full HD: " + officeProjector.supportsFullHD);
        System.out.println("Color: " + officeProjector.projectorColor);
        System.out.println("Width: " + officeProjector.resolutionWidth);
        System.out.println("Height: " + officeProjector.resolutionHeight);
        System.out.println("Contrast: " + officeProjector.contrastRatio);
        System.out.println("Weight: " + officeProjector.projectorWeight);
        System.out.println("Portable: " + officeProjector.isPortable);
        System.out.println("Usage: " + officeProjector.usageType);
        System.out.println("Warranty: " + officeProjector.warrantyYears);
        System.out.println("Country: " + officeProjector.originCountry);
        System.out.println("Price: " + officeProjector.price);

        System.out.println("Mini Projector");
        System.out.println("Brand: " + miniProjector.projectorBrand);
        System.out.println("Technology: " + miniProjector.projectionTechnology);
        System.out.println("Brightness: " + miniProjector.brightnessLumens);
        System.out.println("Quality: " + miniProjector.displayQuality);
        System.out.println("Full HD: " + miniProjector.supportsFullHD);
        System.out.println("Color: " + miniProjector.projectorColor);
        System.out.println("Width: " + miniProjector.resolutionWidth);
        System.out.println("Height: " + miniProjector.resolutionHeight);
        System.out.println("Contrast: " + miniProjector.contrastRatio);
        System.out.println("Weight: " + miniProjector.projectorWeight);
        System.out.println("Portable: " + miniProjector.isPortable);
        System.out.println("Usage: " + miniProjector.usageType);
        System.out.println("Warranty: " + miniProjector.warrantyYears);
        System.out.println("Country: " + miniProjector.originCountry);
        System.out.println("Price: " + miniProjector.price);

        System.out.println("Smart Projector");
        System.out.println("Brand: " + smartProjector.projectorBrand);
        System.out.println("Technology: " + smartProjector.projectionTechnology);
        System.out.println("Brightness: " + smartProjector.brightnessLumens);
        System.out.println("Quality: " + smartProjector.displayQuality);
        System.out.println("Full HD: " + smartProjector.supportsFullHD);
        System.out.println("Color: " + smartProjector.projectorColor);
        System.out.println("Width: " + smartProjector.resolutionWidth);
        System.out.println("Height: " + smartProjector.resolutionHeight);
        System.out.println("Contrast: " + smartProjector.contrastRatio);
        System.out.println("Weight: " + smartProjector.projectorWeight);
        System.out.println("Portable: " + smartProjector.isPortable);
        System.out.println("Usage: " + smartProjector.usageType);
        System.out.println("Warranty: " + smartProjector.warrantyYears);
        System.out.println("Country: " + smartProjector.originCountry);
        System.out.println("Price: " + smartProjector.price);

        System.out.println("Laser Projector");
        System.out.println("Brand: " + laserProjector.projectorBrand);
        System.out.println("Technology: " + laserProjector.projectionTechnology);
        System.out.println("Brightness: " + laserProjector.brightnessLumens);
        System.out.println("Quality: " + laserProjector.displayQuality);
        System.out.println("Full HD: " + laserProjector.supportsFullHD);
        System.out.println("Color: " + laserProjector.projectorColor);
        System.out.println("Width: " + laserProjector.resolutionWidth);
        System.out.println("Height: " + laserProjector.resolutionHeight);
        System.out.println("Contrast: " + laserProjector.contrastRatio);
        System.out.println("Weight: " + laserProjector.projectorWeight);
        System.out.println("Portable: " + laserProjector.isPortable);
        System.out.println("Usage: " + laserProjector.usageType);
        System.out.println("Warranty: " + laserProjector.warrantyYears);
        System.out.println("Country: " + laserProjector.originCountry);
        System.out.println("Price: " + laserProjector.price);

        System.out.println("Portable Projector");
        System.out.println("Brand: " + portableProjector.projectorBrand);
        System.out.println("Technology: " + portableProjector.projectionTechnology);
        System.out.println("Brightness: " + portableProjector.brightnessLumens);
        System.out.println("Quality: " + portableProjector.displayQuality);
        System.out.println("Full HD: " + portableProjector.supportsFullHD);
        System.out.println("Color: " + portableProjector.projectorColor);
        System.out.println("Width: " + portableProjector.resolutionWidth);
        System.out.println("Height: " + portableProjector.resolutionHeight);
        System.out.println("Contrast: " + portableProjector.contrastRatio);
        System.out.println("Weight: " + portableProjector.projectorWeight);
        System.out.println("Portable: " + portableProjector.isPortable);
        System.out.println("Usage: " + portableProjector.usageType);
        System.out.println("Warranty: " + portableProjector.warrantyYears);
        System.out.println("Country: " + portableProjector.originCountry);
        System.out.println("Price: " + portableProjector.price);

        System.out.println("Classroom Projector");
        System.out.println("Brand: " + classroomProjector.projectorBrand);
        System.out.println("Technology: " + classroomProjector.projectionTechnology);
        System.out.println("Brightness: " + classroomProjector.brightnessLumens);
        System.out.println("Quality: " + classroomProjector.displayQuality);
        System.out.println("Full HD: " + classroomProjector.supportsFullHD);
        System.out.println("Color: " + classroomProjector.projectorColor);
        System.out.println("Width: " + classroomProjector.resolutionWidth);
        System.out.println("Height: " + classroomProjector.resolutionHeight);
        System.out.println("Contrast: " + classroomProjector.contrastRatio);
        System.out.println("Weight: " + classroomProjector.projectorWeight);
        System.out.println("Portable: " + classroomProjector.isPortable);
        System.out.println("Usage: " + classroomProjector.usageType);
        System.out.println("Warranty: " + classroomProjector.warrantyYears);
        System.out.println("Country: " + classroomProjector.originCountry);
        System.out.println("Price: " + classroomProjector.price);

        System.out.println("Cinema Projector");
        System.out.println("Brand: " + cinemaProjector.projectorBrand);
        System.out.println("Technology: " + cinemaProjector.projectionTechnology);
        System.out.println("Brightness: " + cinemaProjector.brightnessLumens);
        System.out.println("Quality: " + cinemaProjector.displayQuality);
        System.out.println("Full HD: " + cinemaProjector.supportsFullHD);
        System.out.println("Color: " + cinemaProjector.projectorColor);
        System.out.println("Width: " + cinemaProjector.resolutionWidth);
        System.out.println("Height: " + cinemaProjector.resolutionHeight);
        System.out.println("Contrast: " + cinemaProjector.contrastRatio);
        System.out.println("Weight: " + cinemaProjector.projectorWeight);
        System.out.println("Portable: " + cinemaProjector.isPortable);
        System.out.println("Usage: " + cinemaProjector.usageType);
        System.out.println("Warranty: " + cinemaProjector.warrantyYears);
        System.out.println("Country: " + cinemaProjector.originCountry);
        System.out.println("Price: " + cinemaProjector.price);

        System.out.println("Gaming Projector");
        System.out.println("Brand: " + gamingProjector.projectorBrand);
        System.out.println("Technology: " + gamingProjector.projectionTechnology);
        System.out.println("Brightness: " + gamingProjector.brightnessLumens);
        System.out.println("Quality: " + gamingProjector.displayQuality);
        System.out.println("Full HD: " + gamingProjector.supportsFullHD);
        System.out.println("Color: " + gamingProjector.projectorColor);
        System.out.println("Width: " + gamingProjector.resolutionWidth);
        System.out.println("Height: " + gamingProjector.resolutionHeight);
        System.out.println("Contrast: " + gamingProjector.contrastRatio);
        System.out.println("Weight: " + gamingProjector.projectorWeight);
        System.out.println("Portable: " + gamingProjector.isPortable);
        System.out.println("Usage: " + gamingProjector.usageType);
        System.out.println("Warranty: " + gamingProjector.warrantyYears);
        System.out.println("Country: " + gamingProjector.originCountry);
        System.out.println("Price: " + gamingProjector.price);

        System.out.println("LED Projector");
        System.out.println("Brand: " + ledProjector.projectorBrand);
        System.out.println("Technology: " + ledProjector.projectionTechnology);
        System.out.println("Brightness: " + ledProjector.brightnessLumens);
        System.out.println("Quality: " + ledProjector.displayQuality);
        System.out.println("Full HD: " + ledProjector.supportsFullHD);
        System.out.println("Color: " + ledProjector.projectorColor);
        System.out.println("Width: " + ledProjector.resolutionWidth);
        System.out.println("Height: " + ledProjector.resolutionHeight);
        System.out.println("Contrast: " + ledProjector.contrastRatio);
        System.out.println("Weight: " + ledProjector.projectorWeight);
        System.out.println("Portable: " + ledProjector.isPortable);
        System.out.println("Usage: " + ledProjector.usageType);
        System.out.println("Warranty: " + ledProjector.warrantyYears);
        System.out.println("Country: " + ledProjector.originCountry);
        System.out.println("Price: " + ledProjector.price);
    }
}