class RouterRunner{
    public static void main(String[] args) {

        Router homeRouter = new Router();
        Router officeRouter = new Router();
        Router gamingRouter = new Router();
        Router portableRouter = new Router();
        Router highSpeedRouter = new Router();
        Router compactRouter = new Router();
        Router smartRouter = new Router();
        Router enterpriseRouter = new Router();
        Router premiumRouter = new Router();
        Router advancedRouter = new Router();

        homeRouter.routerColor = "Black";
        homeRouter.antennaCount = 4;
        homeRouter.lanPortCount = 4;
        homeRouter.wanPortCount = 1;
        homeRouter.routerWeight = 0.8;
        homeRouter.isPortable = false;
        homeRouter.usageType = "Home";
        homeRouter.warrantyYears = 2;
        homeRouter.originCountry = "China";
        homeRouter.price = 3000;

        System.out.println("Home Router");
        System.out.println("Brand: " + homeRouter.routerBrand);
        System.out.println("Band: " + homeRouter.frequencyBand);
        System.out.println("Speed: " + homeRouter.speedMbps);
        System.out.println("Performance: " + homeRouter.performanceLevel);
        System.out.println("WiFi6: " + homeRouter.supportsWifi6);
        System.out.println("Color: " + homeRouter.routerColor);
        System.out.println("Antennas: " + homeRouter.antennaCount);
        System.out.println("LAN Ports: " + homeRouter.lanPortCount);
        System.out.println("WAN Ports: " + homeRouter.wanPortCount);
        System.out.println("Weight: " + homeRouter.routerWeight);
        System.out.println("Portable: " + homeRouter.isPortable);
        System.out.println("Usage: " + homeRouter.usageType);
        System.out.println("Warranty: " + homeRouter.warrantyYears);
        System.out.println("Country: " + homeRouter.originCountry);
        System.out.println("Price: " + homeRouter.price);

        System.out.println("Office Router");
        System.out.println("Brand: " + officeRouter.routerBrand);
        System.out.println("Band: " + officeRouter.frequencyBand);
        System.out.println("Speed: " + officeRouter.speedMbps);
        System.out.println("Performance: " + officeRouter.performanceLevel);
        System.out.println("WiFi6: " + officeRouter.supportsWifi6);
        System.out.println("Color: " + officeRouter.routerColor);
        System.out.println("Antennas: " + officeRouter.antennaCount);
        System.out.println("LAN Ports: " + officeRouter.lanPortCount);
        System.out.println("WAN Ports: " + officeRouter.wanPortCount);
        System.out.println("Weight: " + officeRouter.routerWeight);
        System.out.println("Portable: " + officeRouter.isPortable);
        System.out.println("Usage: " + officeRouter.usageType);
        System.out.println("Warranty: " + officeRouter.warrantyYears);
        System.out.println("Country: " + officeRouter.originCountry);
        System.out.println("Price: " + officeRouter.price);

        System.out.println("Gaming Router");
        System.out.println("Brand: " + gamingRouter.routerBrand);
        System.out.println("Band: " + gamingRouter.frequencyBand);
        System.out.println("Speed: " + gamingRouter.speedMbps);
        System.out.println("Performance: " + gamingRouter.performanceLevel);
        System.out.println("WiFi6: " + gamingRouter.supportsWifi6);
        System.out.println("Color: " + gamingRouter.routerColor);
        System.out.println("Antennas: " + gamingRouter.antennaCount);
        System.out.println("LAN Ports: " + gamingRouter.lanPortCount);
        System.out.println("WAN Ports: " + gamingRouter.wanPortCount);
        System.out.println("Weight: " + gamingRouter.routerWeight);
        System.out.println("Portable: " + gamingRouter.isPortable);
        System.out.println("Usage: " + gamingRouter.usageType);
        System.out.println("Warranty: " + gamingRouter.warrantyYears);
        System.out.println("Country: " + gamingRouter.originCountry);
        System.out.println("Price: " + gamingRouter.price);

        System.out.println("Portable Router");
        System.out.println("Brand: " + portableRouter.routerBrand);
        System.out.println("Band: " + portableRouter.frequencyBand);
        System.out.println("Speed: " + portableRouter.speedMbps);
        System.out.println("Performance: " + portableRouter.performanceLevel);
        System.out.println("WiFi6: " + portableRouter.supportsWifi6);
        System.out.println("Color: " + portableRouter.routerColor);
        System.out.println("Antennas: " + portableRouter.antennaCount);
        System.out.println("LAN Ports: " + portableRouter.lanPortCount);
        System.out.println("WAN Ports: " + portableRouter.wanPortCount);
        System.out.println("Weight: " + portableRouter.routerWeight);
        System.out.println("Portable: " + portableRouter.isPortable);
        System.out.println("Usage: " + portableRouter.usageType);
        System.out.println("Warranty: " + portableRouter.warrantyYears);
        System.out.println("Country: " + portableRouter.originCountry);
        System.out.println("Price: " + portableRouter.price);

        System.out.println("High Speed Router");
        System.out.println("Brand: " + highSpeedRouter.routerBrand);
        System.out.println("Band: " + highSpeedRouter.frequencyBand);
        System.out.println("Speed: " + highSpeedRouter.speedMbps);
        System.out.println("Performance: " + highSpeedRouter.performanceLevel);
        System.out.println("WiFi6: " + highSpeedRouter.supportsWifi6);
        System.out.println("Color: " + highSpeedRouter.routerColor);
        System.out.println("Antennas: " + highSpeedRouter.antennaCount);
        System.out.println("LAN Ports: " + highSpeedRouter.lanPortCount);
        System.out.println("WAN Ports: " + highSpeedRouter.wanPortCount);
        System.out.println("Weight: " + highSpeedRouter.routerWeight);
        System.out.println("Portable: " + highSpeedRouter.isPortable);
        System.out.println("Usage: " + highSpeedRouter.usageType);
        System.out.println("Warranty: " + highSpeedRouter.warrantyYears);
        System.out.println("Country: " + highSpeedRouter.originCountry);
        System.out.println("Price: " + highSpeedRouter.price);

        System.out.println("Compact Router");
        System.out.println("Brand: " + compactRouter.routerBrand);
        System.out.println("Band: " + compactRouter.frequencyBand);
        System.out.println("Speed: " + compactRouter.speedMbps);
        System.out.println("Performance: " + compactRouter.performanceLevel);
        System.out.println("WiFi6: " + compactRouter.supportsWifi6);
        System.out.println("Color: " + compactRouter.routerColor);
        System.out.println("Antennas: " + compactRouter.antennaCount);
        System.out.println("LAN Ports: " + compactRouter.lanPortCount);
        System.out.println("WAN Ports: " + compactRouter.wanPortCount);
        System.out.println("Weight: " + compactRouter.routerWeight);
        System.out.println("Portable: " + compactRouter.isPortable);
        System.out.println("Usage: " + compactRouter.usageType);
        System.out.println("Warranty: " + compactRouter.warrantyYears);
        System.out.println("Country: " + compactRouter.originCountry);
        System.out.println("Price: " + compactRouter.price);

        System.out.println("Smart Router");
        System.out.println("Brand: " + smartRouter.routerBrand);
        System.out.println("Band: " + smartRouter.frequencyBand);
        System.out.println("Speed: " + smartRouter.speedMbps);
        System.out.println("Performance: " + smartRouter.performanceLevel);
        System.out.println("WiFi6: " + smartRouter.supportsWifi6);
        System.out.println("Color: " + smartRouter.routerColor);
        System.out.println("Antennas: " + smartRouter.antennaCount);
        System.out.println("LAN Ports: " + smartRouter.lanPortCount);
        System.out.println("WAN Ports: " + smartRouter.wanPortCount);
        System.out.println("Weight: " + smartRouter.routerWeight);
        System.out.println("Portable: " + smartRouter.isPortable);
        System.out.println("Usage: " + smartRouter.usageType);
        System.out.println("Warranty: " + smartRouter.warrantyYears);
        System.out.println("Country: " + smartRouter.originCountry);
        System.out.println("Price: " + smartRouter.price);

        System.out.println("Enterprise Router");
        System.out.println("Brand: " + enterpriseRouter.routerBrand);
        System.out.println("Band: " + enterpriseRouter.frequencyBand);
        System.out.println("Speed: " + enterpriseRouter.speedMbps);
        System.out.println("Performance: " + enterpriseRouter.performanceLevel);
        System.out.println("WiFi6: " + enterpriseRouter.supportsWifi6);
        System.out.println("Color: " + enterpriseRouter.routerColor);
        System.out.println("Antennas: " + enterpriseRouter.antennaCount);
        System.out.println("LAN Ports: " + enterpriseRouter.lanPortCount);
        System.out.println("WAN Ports: " + enterpriseRouter.wanPortCount);
        System.out.println("Weight: " + enterpriseRouter.routerWeight);
        System.out.println("Portable: " + enterpriseRouter.isPortable);
        System.out.println("Usage: " + enterpriseRouter.usageType);
        System.out.println("Warranty: " + enterpriseRouter.warrantyYears);
        System.out.println("Country: " + enterpriseRouter.originCountry);
        System.out.println("Price: " + enterpriseRouter.price);

        System.out.println("Premium Router");
        System.out.println("Brand: " + premiumRouter.routerBrand);
        System.out.println("Band: " + premiumRouter.frequencyBand);
        System.out.println("Speed: " + premiumRouter.speedMbps);
        System.out.println("Performance: " + premiumRouter.performanceLevel);
        System.out.println("WiFi6: " + premiumRouter.supportsWifi6);
        System.out.println("Color: " + premiumRouter.routerColor);
        System.out.println("Antennas: " + premiumRouter.antennaCount);
        System.out.println("LAN Ports: " + premiumRouter.lanPortCount);
        System.out.println("WAN Ports: " + premiumRouter.wanPortCount);
        System.out.println("Weight: " + premiumRouter.routerWeight);
        System.out.println("Portable: " + premiumRouter.isPortable);
        System.out.println("Usage: " + premiumRouter.usageType);
        System.out.println("Warranty: " + premiumRouter.warrantyYears);
        System.out.println("Country: " + premiumRouter.originCountry);
        System.out.println("Price: " + premiumRouter.price);

        System.out.println("Advanced Router");
        System.out.println("Brand: " + advancedRouter.routerBrand);
        System.out.println("Band: " + advancedRouter.frequencyBand);
        System.out.println("Speed: " + advancedRouter.speedMbps);
        System.out.println("Performance: " + advancedRouter.performanceLevel);
        System.out.println("WiFi6: " + advancedRouter.supportsWifi6);
        System.out.println("Color: " + advancedRouter.routerColor);
        System.out.println("Antennas: " + advancedRouter.antennaCount);
        System.out.println("LAN Ports: " + advancedRouter.lanPortCount);
        System.out.println("WAN Ports: " + advancedRouter.wanPortCount);
        System.out.println("Weight: " + advancedRouter.routerWeight);
        System.out.println("Portable: " + advancedRouter.isPortable);
        System.out.println("Usage: " + advancedRouter.usageType);
        System.out.println("Warranty: " + advancedRouter.warrantyYears);
        System.out.println("Country: " + advancedRouter.originCountry);
        System.out.println("Price: " + advancedRouter.price);
    }
}