class SatelliteRunner{
    public static void main(String[] args){

        Satellite communicationSatellite = new Satellite();
        Satellite weatherSatellite = new Satellite();
        Satellite gpsSatellite = new Satellite();
        Satellite militarySatellite = new Satellite();
        Satellite researchSatellite = new Satellite();
        Satellite navigationSatellite = new Satellite();
        Satellite earthObservationSatellite = new Satellite();
        Satellite spaceStationSatellite = new Satellite();
        Satellite experimentalSatellite = new Satellite();
        Satellite advancedSatellite = new Satellite();

        communicationSatellite.purpose = "Communication";
        communicationSatellite.altitudeKm = 36000;
        communicationSatellite.lifespanYears = 15;
        communicationSatellite.signalFrequencyGHz = 12;
        communicationSatellite.satelliteWeight = 2500;
        communicationSatellite.isGovernmentOwned = true;
        communicationSatellite.launchVehicle = "PSLV";
        communicationSatellite.warrantyYears = 5;
        communicationSatellite.originCountry = "India";
        communicationSatellite.maintenanceCost = 1000;

        System.out.println("Communication Satellite");
        System.out.println("Name: " + communicationSatellite.satelliteName);
        System.out.println("Orbit: " + communicationSatellite.orbitType);
        System.out.println("Launch Year: " + communicationSatellite.launchYear);
        System.out.println("Performance: " + communicationSatellite.performanceLevel);
        System.out.println("Active: " + communicationSatellite.isActive);
        System.out.println("Purpose: " + communicationSatellite.purpose);
        System.out.println("Altitude: " + communicationSatellite.altitudeKm);
        System.out.println("Lifespan: " + communicationSatellite.lifespanYears);
        System.out.println("Frequency: " + communicationSatellite.signalFrequencyGHz);
        System.out.println("Weight: " + communicationSatellite.satelliteWeight);
        System.out.println("Government: " + communicationSatellite.isGovernmentOwned);
        System.out.println("Launch Vehicle: " + communicationSatellite.launchVehicle);
        System.out.println("Warranty: " + communicationSatellite.warrantyYears);
        System.out.println("Country: " + communicationSatellite.originCountry);
        System.out.println("Maintenance: " + communicationSatellite.maintenanceCost);

        System.out.println("Weather Satellite");
        System.out.println("Name: " + weatherSatellite.satelliteName);
        System.out.println("Orbit: " + weatherSatellite.orbitType);
        System.out.println("Launch Year: " + weatherSatellite.launchYear);
        System.out.println("Performance: " + weatherSatellite.performanceLevel);
        System.out.println("Active: " + weatherSatellite.isActive);
        System.out.println("Purpose: " + weatherSatellite.purpose);
        System.out.println("Altitude: " + weatherSatellite.altitudeKm);
        System.out.println("Lifespan: " + weatherSatellite.lifespanYears);
        System.out.println("Frequency: " + weatherSatellite.signalFrequencyGHz);
        System.out.println("Weight: " + weatherSatellite.satelliteWeight);
        System.out.println("Government: " + weatherSatellite.isGovernmentOwned);
        System.out.println("Launch Vehicle: " + weatherSatellite.launchVehicle);
        System.out.println("Warranty: " + weatherSatellite.warrantyYears);
        System.out.println("Country: " + weatherSatellite.originCountry);
        System.out.println("Maintenance: " + weatherSatellite.maintenanceCost);

        System.out.println("GPS Satellite");
        System.out.println("Name: " + gpsSatellite.satelliteName);
        System.out.println("Orbit: " + gpsSatellite.orbitType);
        System.out.println("Launch Year: " + gpsSatellite.launchYear);
        System.out.println("Performance: " + gpsSatellite.performanceLevel);
        System.out.println("Active: " + gpsSatellite.isActive);
        System.out.println("Purpose: " + gpsSatellite.purpose);
        System.out.println("Altitude: " + gpsSatellite.altitudeKm);
        System.out.println("Lifespan: " + gpsSatellite.lifespanYears);
        System.out.println("Frequency: " + gpsSatellite.signalFrequencyGHz);
        System.out.println("Weight: " + gpsSatellite.satelliteWeight);
        System.out.println("Government: " + gpsSatellite.isGovernmentOwned);
        System.out.println("Launch Vehicle: " + gpsSatellite.launchVehicle);
        System.out.println("Warranty: " + gpsSatellite.warrantyYears);
        System.out.println("Country: " + gpsSatellite.originCountry);
        System.out.println("Maintenance: " + gpsSatellite.maintenanceCost);

        System.out.println("Military Satellite");
        System.out.println("Name: " + militarySatellite.satelliteName);
        System.out.println("Orbit: " + militarySatellite.orbitType);
        System.out.println("Launch Year: " + militarySatellite.launchYear);
        System.out.println("Performance: " + militarySatellite.performanceLevel);
        System.out.println("Active: " + militarySatellite.isActive);
        System.out.println("Purpose: " + militarySatellite.purpose);
        System.out.println("Altitude: " + militarySatellite.altitudeKm);
        System.out.println("Lifespan: " + militarySatellite.lifespanYears);
        System.out.println("Frequency: " + militarySatellite.signalFrequencyGHz);
        System.out.println("Weight: " + militarySatellite.satelliteWeight);
        System.out.println("Government: " + militarySatellite.isGovernmentOwned);
        System.out.println("Launch Vehicle: " + militarySatellite.launchVehicle);
        System.out.println("Warranty: " + militarySatellite.warrantyYears);
        System.out.println("Country: " + militarySatellite.originCountry);
        System.out.println("Maintenance: " + militarySatellite.maintenanceCost);

        System.out.println("Research Satellite");
        System.out.println("Name: " + researchSatellite.satelliteName);
        System.out.println("Orbit: " + researchSatellite.orbitType);
        System.out.println("Launch Year: " + researchSatellite.launchYear);
        System.out.println("Performance: " + researchSatellite.performanceLevel);
        System.out.println("Active: " + researchSatellite.isActive);
        System.out.println("Purpose: " + researchSatellite.purpose);
        System.out.println("Altitude: " + researchSatellite.altitudeKm);
        System.out.println("Lifespan: " + researchSatellite.lifespanYears);
        System.out.println("Frequency: " + researchSatellite.signalFrequencyGHz);
        System.out.println("Weight: " + researchSatellite.satelliteWeight);
        System.out.println("Government: " + researchSatellite.isGovernmentOwned);
        System.out.println("Launch Vehicle: " + researchSatellite.launchVehicle);
        System.out.println("Warranty: " + researchSatellite.warrantyYears);
        System.out.println("Country: " + researchSatellite.originCountry);
        System.out.println("Maintenance: " + researchSatellite.maintenanceCost);

        System.out.println("Navigation Satellite");
        System.out.println("Name: " + navigationSatellite.satelliteName);
        System.out.println("Orbit: " + navigationSatellite.orbitType);
        System.out.println("Launch Year: " + navigationSatellite.launchYear);
        System.out.println("Performance: " + navigationSatellite.performanceLevel);
        System.out.println("Active: " + navigationSatellite.isActive);
        System.out.println("Purpose: " + navigationSatellite.purpose);
        System.out.println("Altitude: " + navigationSatellite.altitudeKm);
        System.out.println("Lifespan: " + navigationSatellite.lifespanYears);
        System.out.println("Frequency: " + navigationSatellite.signalFrequencyGHz);
        System.out.println("Weight: " + navigationSatellite.satelliteWeight);
        System.out.println("Government: " + navigationSatellite.isGovernmentOwned);
        System.out.println("Launch Vehicle: " + navigationSatellite.launchVehicle);
        System.out.println("Warranty: " + navigationSatellite.warrantyYears);
        System.out.println("Country: " + navigationSatellite.originCountry);
        System.out.println("Maintenance: " + navigationSatellite.maintenanceCost);

        System.out.println("Earth Observation Satellite");
        System.out.println("Name: " + earthObservationSatellite.satelliteName);
        System.out.println("Orbit: " + earthObservationSatellite.orbitType);
        System.out.println("Launch Year: " + earthObservationSatellite.launchYear);
        System.out.println("Performance: " + earthObservationSatellite.performanceLevel);
        System.out.println("Active: " + earthObservationSatellite.isActive);
        System.out.println("Purpose: " + earthObservationSatellite.purpose);
        System.out.println("Altitude: " + earthObservationSatellite.altitudeKm);
        System.out.println("Lifespan: " + earthObservationSatellite.lifespanYears);
        System.out.println("Frequency: " + earthObservationSatellite.signalFrequencyGHz);
        System.out.println("Weight: " + earthObservationSatellite.satelliteWeight);
        System.out.println("Government: " + earthObservationSatellite.isGovernmentOwned);
        System.out.println("Launch Vehicle: " + earthObservationSatellite.launchVehicle);
        System.out.println("Warranty: " + earthObservationSatellite.warrantyYears);
        System.out.println("Country: " + earthObservationSatellite.originCountry);
        System.out.println("Maintenance: " + earthObservationSatellite.maintenanceCost);

        System.out.println("Space Station Satellite");
        System.out.println("Name: " + spaceStationSatellite.satelliteName);
        System.out.println("Orbit: " + spaceStationSatellite.orbitType);
        System.out.println("Launch Year: " + spaceStationSatellite.launchYear);
        System.out.println("Performance: " + spaceStationSatellite.performanceLevel);
        System.out.println("Active: " + spaceStationSatellite.isActive);
        System.out.println("Purpose: " + spaceStationSatellite.purpose);
        System.out.println("Altitude: " + spaceStationSatellite.altitudeKm);
        System.out.println("Lifespan: " + spaceStationSatellite.lifespanYears);
        System.out.println("Frequency: " + spaceStationSatellite.signalFrequencyGHz);
        System.out.println("Weight: " + spaceStationSatellite.satelliteWeight);
        System.out.println("Government: " + spaceStationSatellite.isGovernmentOwned);
        System.out.println("Launch Vehicle: " + spaceStationSatellite.launchVehicle);
        System.out.println("Warranty: " + spaceStationSatellite.warrantyYears);
        System.out.println("Country: " + spaceStationSatellite.originCountry);
        System.out.println("Maintenance: " + spaceStationSatellite.maintenanceCost);

        System.out.println("Experimental Satellite");
        System.out.println("Name: " + experimentalSatellite.satelliteName);
        System.out.println("Orbit: " + experimentalSatellite.orbitType);
        System.out.println("Launch Year: " + experimentalSatellite.launchYear);
        System.out.println("Performance: " + experimentalSatellite.performanceLevel);
        System.out.println("Active: " + experimentalSatellite.isActive);
        System.out.println("Purpose: " + experimentalSatellite.purpose);
        System.out.println("Altitude: " + experimentalSatellite.altitudeKm);
        System.out.println("Lifespan: " + experimentalSatellite.lifespanYears);
        System.out.println("Frequency: " + experimentalSatellite.signalFrequencyGHz);
        System.out.println("Weight: " + experimentalSatellite.satelliteWeight);
        System.out.println("Government: " + experimentalSatellite.isGovernmentOwned);
        System.out.println("Launch Vehicle: " + experimentalSatellite.launchVehicle);
        System.out.println("Warranty: " + experimentalSatellite.warrantyYears);
        System.out.println("Country: " + experimentalSatellite.originCountry);
        System.out.println("Maintenance: " + experimentalSatellite.maintenanceCost);

        System.out.println("Advanced Satellite");
        System.out.println("Name: " + advancedSatellite.satelliteName);
        System.out.println("Orbit: " + advancedSatellite.orbitType);
        System.out.println("Launch Year: " + advancedSatellite.launchYear);
        System.out.println("Performance: " + advancedSatellite.performanceLevel);
        System.out.println("Active: " + advancedSatellite.isActive);
        System.out.println("Purpose: " + advancedSatellite.purpose);
        System.out.println("Altitude: " + advancedSatellite.altitudeKm);
        System.out.println("Lifespan: " + advancedSatellite.lifespanYears);
        System.out.println("Frequency: " + advancedSatellite.signalFrequencyGHz);
        System.out.println("Weight: " + advancedSatellite.satelliteWeight);
        System.out.println("Government: " + advancedSatellite.isGovernmentOwned);
        System.out.println("Launch Vehicle: " + advancedSatellite.launchVehicle);
        System.out.println("Warranty: " + advancedSatellite.warrantyYears);
        System.out.println("Country: " + advancedSatellite.originCountry);
        System.out.println("Maintenance: " + advancedSatellite.maintenanceCost);
    }
}