class XboxRunner{
    public static void main(String[] args){

        Xbox gamingXbox = new Xbox();
        Xbox homeXbox = new Xbox();
        Xbox slimXbox = new Xbox();
        Xbox proXbox = new Xbox();
        Xbox digitalXbox = new Xbox();
        Xbox portableXbox = new Xbox();
        Xbox classicXbox = new Xbox();
        Xbox eliteXbox = new Xbox();
        Xbox miniXbox = new Xbox();
        Xbox advancedXbox = new Xbox();

        gamingXbox.consoleColor = "Black";
        gamingXbox.ramSizeGB = 16;
        gamingXbox.usbPortCount = 3;
        gamingXbox.hdmiPortCount = 1;
        gamingXbox.consoleWeight = 4.5;
        gamingXbox.isOnlineEnabled = true;
        gamingXbox.processorType = "AMD";
        gamingXbox.warrantyYears = 2;
        gamingXbox.originCountry = "USA";
        gamingXbox.price = 55000;

        System.out.println("Gaming Xbox");
        System.out.println("Brand: " + gamingXbox.consoleBrand);
        System.out.println("Model: " + gamingXbox.consoleModel);
        System.out.println("Storage: " + gamingXbox.storageCapacityGB);
        System.out.println("Performance: " + gamingXbox.performanceLevel);
        System.out.println("4K Support: " + gamingXbox.supports4K);
        System.out.println("Color: " + gamingXbox.consoleColor);
        System.out.println("RAM: " + gamingXbox.ramSizeGB);
        System.out.println("USB Ports: " + gamingXbox.usbPortCount);
        System.out.println("HDMI Ports: " + gamingXbox.hdmiPortCount);
        System.out.println("Weight: " + gamingXbox.consoleWeight);
        System.out.println("Online: " + gamingXbox.isOnlineEnabled);
        System.out.println("Processor: " + gamingXbox.processorType);
        System.out.println("Warranty: " + gamingXbox.warrantyYears);
        System.out.println("Country: " + gamingXbox.originCountry);
        System.out.println("Price: " + gamingXbox.price);

        System.out.println("Home Xbox");
        System.out.println("Brand: " + homeXbox.consoleBrand);
        System.out.println("Model: " + homeXbox.consoleModel);
        System.out.println("Storage: " + homeXbox.storageCapacityGB);
        System.out.println("Performance: " + homeXbox.performanceLevel);
        System.out.println("4K Support: " + homeXbox.supports4K);
        System.out.println("Color: " + homeXbox.consoleColor);
        System.out.println("RAM: " + homeXbox.ramSizeGB);
        System.out.println("USB Ports: " + homeXbox.usbPortCount);
        System.out.println("HDMI Ports: " + homeXbox.hdmiPortCount);
        System.out.println("Weight: " + homeXbox.consoleWeight);
        System.out.println("Online: " + homeXbox.isOnlineEnabled);
        System.out.println("Processor: " + homeXbox.processorType);
        System.out.println("Warranty: " + homeXbox.warrantyYears);
        System.out.println("Country: " + homeXbox.originCountry);
        System.out.println("Price: " + homeXbox.price);

        System.out.println("Slim Xbox");
        System.out.println("Brand: " + slimXbox.consoleBrand);
        System.out.println("Model: " + slimXbox.consoleModel);
        System.out.println("Storage: " + slimXbox.storageCapacityGB);
        System.out.println("Performance: " + slimXbox.performanceLevel);
        System.out.println("4K Support: " + slimXbox.supports4K);
        System.out.println("Color: " + slimXbox.consoleColor);
        System.out.println("RAM: " + slimXbox.ramSizeGB);
        System.out.println("USB Ports: " + slimXbox.usbPortCount);
        System.out.println("HDMI Ports: " + slimXbox.hdmiPortCount);
        System.out.println("Weight: " + slimXbox.consoleWeight);
        System.out.println("Online: " + slimXbox.isOnlineEnabled);
        System.out.println("Processor: " + slimXbox.processorType);
        System.out.println("Warranty: " + slimXbox.warrantyYears);
        System.out.println("Country: " + slimXbox.originCountry);
        System.out.println("Price: " + slimXbox.price);

        System.out.println("Pro Xbox");
        System.out.println("Brand: " + proXbox.consoleBrand);
        System.out.println("Model: " + proXbox.consoleModel);
        System.out.println("Storage: " + proXbox.storageCapacityGB);
        System.out.println("Performance: " + proXbox.performanceLevel);
        System.out.println("4K Support: " + proXbox.supports4K);
        System.out.println("Color: " + proXbox.consoleColor);
        System.out.println("RAM: " + proXbox.ramSizeGB);
        System.out.println("USB Ports: " + proXbox.usbPortCount);
        System.out.println("HDMI Ports: " + proXbox.hdmiPortCount);
        System.out.println("Weight: " + proXbox.consoleWeight);
        System.out.println("Online: " + proXbox.isOnlineEnabled);
        System.out.println("Processor: " + proXbox.processorType);
        System.out.println("Warranty: " + proXbox.warrantyYears);
        System.out.println("Country: " + proXbox.originCountry);
        System.out.println("Price: " + proXbox.price);

        System.out.println("Digital Xbox");
        System.out.println("Brand: " + digitalXbox.consoleBrand);
        System.out.println("Model: " + digitalXbox.consoleModel);
        System.out.println("Storage: " + digitalXbox.storageCapacityGB);
        System.out.println("Performance: " + digitalXbox.performanceLevel);
        System.out.println("4K Support: " + digitalXbox.supports4K);
        System.out.println("Color: " + digitalXbox.consoleColor);
        System.out.println("RAM: " + digitalXbox.ramSizeGB);
        System.out.println("USB Ports: " + digitalXbox.usbPortCount);
        System.out.println("HDMI Ports: " + digitalXbox.hdmiPortCount);
        System.out.println("Weight: " + digitalXbox.consoleWeight);
        System.out.println("Online: " + digitalXbox.isOnlineEnabled);
        System.out.println("Processor: " + digitalXbox.processorType);
        System.out.println("Warranty: " + digitalXbox.warrantyYears);
        System.out.println("Country: " + digitalXbox.originCountry);
        System.out.println("Price: " + digitalXbox.price);

        System.out.println("Portable Xbox");
        System.out.println("Brand: " + portableXbox.consoleBrand);
        System.out.println("Model: " + portableXbox.consoleModel);
        System.out.println("Storage: " + portableXbox.storageCapacityGB);
        System.out.println("Performance: " + portableXbox.performanceLevel);
        System.out.println("4K Support: " + portableXbox.supports4K);
        System.out.println("Color: " + portableXbox.consoleColor);
        System.out.println("RAM: " + portableXbox.ramSizeGB);
        System.out.println("USB Ports: " + portableXbox.usbPortCount);
        System.out.println("HDMI Ports: " + portableXbox.hdmiPortCount);
        System.out.println("Weight: " + portableXbox.consoleWeight);
        System.out.println("Online: " + portableXbox.isOnlineEnabled);
        System.out.println("Processor: " + portableXbox.processorType);
        System.out.println("Warranty: " + portableXbox.warrantyYears);
        System.out.println("Country: " + portableXbox.originCountry);
        System.out.println("Price: " + portableXbox.price);

        System.out.println("Classic Xbox");
        System.out.println("Brand: " + classicXbox.consoleBrand);
        System.out.println("Model: " + classicXbox.consoleModel);
        System.out.println("Storage: " + classicXbox.storageCapacityGB);
        System.out.println("Performance: " + classicXbox.performanceLevel);
        System.out.println("4K Support: " + classicXbox.supports4K);
        System.out.println("Color: " + classicXbox.consoleColor);
        System.out.println("RAM: " + classicXbox.ramSizeGB);
        System.out.println("USB Ports: " + classicXbox.usbPortCount);
        System.out.println("HDMI Ports: " + classicXbox.hdmiPortCount);
        System.out.println("Weight: " + classicXbox.consoleWeight);
        System.out.println("Online: " + classicXbox.isOnlineEnabled);
        System.out.println("Processor: " + classicXbox.processorType);
        System.out.println("Warranty: " + classicXbox.warrantyYears);
        System.out.println("Country: " + classicXbox.originCountry);
        System.out.println("Price: " + classicXbox.price);

        System.out.println("Elite Xbox");
        System.out.println("Brand: " + eliteXbox.consoleBrand);
        System.out.println("Model: " + eliteXbox.consoleModel);
        System.out.println("Storage: " + eliteXbox.storageCapacityGB);
        System.out.println("Performance: " + eliteXbox.performanceLevel);
        System.out.println("4K Support: " + eliteXbox.supports4K);
        System.out.println("Color: " + eliteXbox.consoleColor);
        System.out.println("RAM: " + eliteXbox.ramSizeGB);
        System.out.println("USB Ports: " + eliteXbox.usbPortCount);
        System.out.println("HDMI Ports: " + eliteXbox.hdmiPortCount);
        System.out.println("Weight: " + eliteXbox.consoleWeight);
        System.out.println("Online: " + eliteXbox.isOnlineEnabled);
        System.out.println("Processor: " + eliteXbox.processorType);
        System.out.println("Warranty: " + eliteXbox.warrantyYears);
        System.out.println("Country: " + eliteXbox.originCountry);
        System.out.println("Price: " + eliteXbox.price);

        System.out.println("Mini Xbox");
        System.out.println("Brand: " + miniXbox.consoleBrand);
        System.out.println("Model: " + miniXbox.consoleModel);
        System.out.println("Storage: " + miniXbox.storageCapacityGB);
        System.out.println("Performance: " + miniXbox.performanceLevel);
        System.out.println("4K Support: " + miniXbox.supports4K);
        System.out.println("Color: " + miniXbox.consoleColor);
        System.out.println("RAM: " + miniXbox.ramSizeGB);
        System.out.println("USB Ports: " + miniXbox.usbPortCount);
        System.out.println("HDMI Ports: " + miniXbox.hdmiPortCount);
        System.out.println("Weight: " + miniXbox.consoleWeight);
        System.out.println("Online: " + miniXbox.isOnlineEnabled);
        System.out.println("Processor: " + miniXbox.processorType);
        System.out.println("Warranty: " + miniXbox.warrantyYears);
        System.out.println("Country: " + miniXbox.originCountry);
        System.out.println("Price: " + miniXbox.price);

        System.out.println("Advanced Xbox");
        System.out.println("Brand: " + advancedXbox.consoleBrand);
        System.out.println("Model: " + advancedXbox.consoleModel);
        System.out.println("Storage: " + advancedXbox.storageCapacityGB);
        System.out.println("Performance: " + advancedXbox.performanceLevel);
        System.out.println("4K Support: " + advancedXbox.supports4K);
        System.out.println("Color: " + advancedXbox.consoleColor);
        System.out.println("RAM: " + advancedXbox.ramSizeGB);
        System.out.println("USB Ports: " + advancedXbox.usbPortCount);
        System.out.println("HDMI Ports: " + advancedXbox.hdmiPortCount);
        System.out.println("Weight: " + advancedXbox.consoleWeight);
        System.out.println("Online: " + advancedXbox.isOnlineEnabled);
        System.out.println("Processor: " + advancedXbox.processorType);
        System.out.println("Warranty: " + advancedXbox.warrantyYears);
        System.out.println("Country: " + advancedXbox.originCountry);
        System.out.println("Price: " + advancedXbox.price);
    }
}