class ZipRunner{
    public static void main(String[] args) {

        Zip backupZip = new Zip();
        Zip archiveZip = new Zip();
        Zip mediaZip = new Zip();
        Zip documentZip = new Zip();
        Zip secureZip = new Zip();
        Zip compressedZip = new Zip();
        Zip largeZip = new Zip();
        Zip smallZip = new Zip();
        Zip fastZip = new Zip();
        Zip advancedZip = new Zip();

        backupZip.fileName = "backup.zip";
        backupZip.fileSizeMB = 500;
        backupZip.compressedSizeMB = 200;
        backupZip.numberOfFiles = 50;
        backupZip.processingTime = 1.5;
        backupZip.isEncrypted = true;
        backupZip.usageType = "Backup";
        backupZip.version = 2;
        backupZip.originSoftware = "WinZip";
        backupZip.efficiencyRate = 85.5;

        System.out.println("Backup Zip");
        System.out.println("Format: " + backupZip.fileFormat);
        System.out.println("Compression: " + backupZip.compressionType);
        System.out.println("Level: " + backupZip.compressionLevel);
        System.out.println("Ratio: " + backupZip.compressionRatio);
        System.out.println("Password: " + backupZip.isPasswordProtected);
        System.out.println("File Name: " + backupZip.fileName);
        System.out.println("File Size: " + backupZip.fileSizeMB);
        System.out.println("Compressed Size: " + backupZip.compressedSizeMB);
        System.out.println("Files: " + backupZip.numberOfFiles);
        System.out.println("Time: " + backupZip.processingTime);
        System.out.println("Encrypted: " + backupZip.isEncrypted);
        System.out.println("Usage: " + backupZip.usageType);
        System.out.println("Version: " + backupZip.version);
        System.out.println("Software: " + backupZip.originSoftware);
        System.out.println("Efficiency: " + backupZip.efficiencyRate);

        System.out.println("Archive Zip");
        System.out.println("Format: " + archiveZip.fileFormat);
        System.out.println("Compression: " + archiveZip.compressionType);
        System.out.println("Level: " + archiveZip.compressionLevel);
        System.out.println("Ratio: " + archiveZip.compressionRatio);
        System.out.println("Password: " + archiveZip.isPasswordProtected);
        System.out.println("File Name: " + archiveZip.fileName);
        System.out.println("File Size: " + archiveZip.fileSizeMB);
        System.out.println("Compressed Size: " + archiveZip.compressedSizeMB);
        System.out.println("Files: " + archiveZip.numberOfFiles);
        System.out.println("Time: " + archiveZip.processingTime);
        System.out.println("Encrypted: " + archiveZip.isEncrypted);
        System.out.println("Usage: " + archiveZip.usageType);
        System.out.println("Version: " + archiveZip.version);
        System.out.println("Software: " + archiveZip.originSoftware);
        System.out.println("Efficiency: " + archiveZip.efficiencyRate);

        System.out.println("Media Zip");
        System.out.println("Format: " + mediaZip.fileFormat);
        System.out.println("Compression: " + mediaZip.compressionType);
        System.out.println("Level: " + mediaZip.compressionLevel);
        System.out.println("Ratio: " + mediaZip.compressionRatio);
        System.out.println("Password: " + mediaZip.isPasswordProtected);
        System.out.println("File Name: " + mediaZip.fileName);
        System.out.println("File Size: " + mediaZip.fileSizeMB);
        System.out.println("Compressed Size: " + mediaZip.compressedSizeMB);
        System.out.println("Files: " + mediaZip.numberOfFiles);
        System.out.println("Time: " + mediaZip.processingTime);
        System.out.println("Encrypted: " + mediaZip.isEncrypted);
        System.out.println("Usage: " + mediaZip.usageType);
        System.out.println("Version: " + mediaZip.version);
        System.out.println("Software: " + mediaZip.originSoftware);
        System.out.println("Efficiency: " + mediaZip.efficiencyRate);

        System.out.println("Document Zip");
        System.out.println("Format: " + documentZip.fileFormat);
        System.out.println("Compression: " + documentZip.compressionType);
        System.out.println("Level: " + documentZip.compressionLevel);
        System.out.println("Ratio: " + documentZip.compressionRatio);
        System.out.println("Password: " + documentZip.isPasswordProtected);
        System.out.println("File Name: " + documentZip.fileName);
        System.out.println("File Size: " + documentZip.fileSizeMB);
        System.out.println("Compressed Size: " + documentZip.compressedSizeMB);
        System.out.println("Files: " + documentZip.numberOfFiles);
        System.out.println("Time: " + documentZip.processingTime);
        System.out.println("Encrypted: " + documentZip.isEncrypted);
        System.out.println("Usage: " + documentZip.usageType);
        System.out.println("Version: " + documentZip.version);
        System.out.println("Software: " + documentZip.originSoftware);
        System.out.println("Efficiency: " + documentZip.efficiencyRate);

        System.out.println("Secure Zip");
        System.out.println("Format: " + secureZip.fileFormat);
        System.out.println("Compression: " + secureZip.compressionType);
        System.out.println("Level: " + secureZip.compressionLevel);
        System.out.println("Ratio: " + secureZip.compressionRatio);
        System.out.println("Password: " + secureZip.isPasswordProtected);
        System.out.println("File Name: " + secureZip.fileName);
        System.out.println("File Size: " + secureZip.fileSizeMB);
        System.out.println("Compressed Size: " + secureZip.compressedSizeMB);
        System.out.println("Files: " + secureZip.numberOfFiles);
        System.out.println("Time: " + secureZip.processingTime);
        System.out.println("Encrypted: " + secureZip.isEncrypted);
        System.out.println("Usage: " + secureZip.usageType);
        System.out.println("Version: " + secureZip.version);
        System.out.println("Software: " + secureZip.originSoftware);
        System.out.println("Efficiency: " + secureZip.efficiencyRate);

        System.out.println("Compressed Zip");
        System.out.println("Format: " + compressedZip.fileFormat);
        System.out.println("Compression: " + compressedZip.compressionType);
        System.out.println("Level: " + compressedZip.compressionLevel);
        System.out.println("Ratio: " + compressedZip.compressionRatio);
        System.out.println("Password: " + compressedZip.isPasswordProtected);
        System.out.println("File Name: " + compressedZip.fileName);
        System.out.println("File Size: " + compressedZip.fileSizeMB);
        System.out.println("Compressed Size: " + compressedZip.compressedSizeMB);
        System.out.println("Files: " + compressedZip.numberOfFiles);
        System.out.println("Time: " + compressedZip.processingTime);
        System.out.println("Encrypted: " + compressedZip.isEncrypted);
        System.out.println("Usage: " + compressedZip.usageType);
        System.out.println("Version: " + compressedZip.version);
        System.out.println("Software: " + compressedZip.originSoftware);
        System.out.println("Efficiency: " + compressedZip.efficiencyRate);

        System.out.println("Large Zip");
        System.out.println("Format: " + largeZip.fileFormat);
        System.out.println("Compression: " + largeZip.compressionType);
        System.out.println("Level: " + largeZip.compressionLevel);
        System.out.println("Ratio: " + largeZip.compressionRatio);
        System.out.println("Password: " + largeZip.isPasswordProtected);
        System.out.println("File Name: " + largeZip.fileName);
        System.out.println("File Size: " + largeZip.fileSizeMB);
        System.out.println("Compressed Size: " + largeZip.compressedSizeMB);
        System.out.println("Files: " + largeZip.numberOfFiles);
        System.out.println("Time: " + largeZip.processingTime);
        System.out.println("Encrypted: " + largeZip.isEncrypted);
        System.out.println("Usage: " + largeZip.usageType);
        System.out.println("Version: " + largeZip.version);
        System.out.println("Software: " + largeZip.originSoftware);
        System.out.println("Efficiency: " + largeZip.efficiencyRate);

        System.out.println("Small Zip");
        System.out.println("Format: " + smallZip.fileFormat);
        System.out.println("Compression: " + smallZip.compressionType);
        System.out.println("Level: " + smallZip.compressionLevel);
        System.out.println("Ratio: " + smallZip.compressionRatio);
        System.out.println("Password: " + smallZip.isPasswordProtected);
        System.out.println("File Name: " + smallZip.fileName);
        System.out.println("File Size: " + smallZip.fileSizeMB);
        System.out.println("Compressed Size: " + smallZip.compressedSizeMB);
        System.out.println("Files: " + smallZip.numberOfFiles);
        System.out.println("Time: " + smallZip.processingTime);
        System.out.println("Encrypted: " + smallZip.isEncrypted);
        System.out.println("Usage: " + smallZip.usageType);
        System.out.println("Version: " + smallZip.version);
        System.out.println("Software: " + smallZip.originSoftware);
        System.out.println("Efficiency: " + smallZip.efficiencyRate);

        System.out.println("Fast Zip");
        System.out.println("Format: " + fastZip.fileFormat);
        System.out.println("Compression: " + fastZip.compressionType);
        System.out.println("Level: " + fastZip.compressionLevel);
        System.out.println("Ratio: " + fastZip.compressionRatio);
        System.out.println("Password: " + fastZip.isPasswordProtected);
        System.out.println("File Name: " + fastZip.fileName);
        System.out.println("File Size: " + fastZip.fileSizeMB);
        System.out.println("Compressed Size: " + fastZip.compressedSizeMB);
        System.out.println("Files: " + fastZip.numberOfFiles);
        System.out.println("Time: " + fastZip.processingTime);
        System.out.println("Encrypted: " + fastZip.isEncrypted);
        System.out.println("Usage: " + fastZip.usageType);
        System.out.println("Version: " + fastZip.version);
        System.out.println("Software: " + fastZip.originSoftware);
        System.out.println("Efficiency: " + fastZip.efficiencyRate);

        System.out.println("Advanced Zip");
        System.out.println("Format: " + advancedZip.fileFormat);
        System.out.println("Compression: " + advancedZip.compressionType);
        System.out.println("Level: " + advancedZip.compressionLevel);
        System.out.println("Ratio: " + advancedZip.compressionRatio);
        System.out.println("Password: " + advancedZip.isPasswordProtected);
        System.out.println("File Name: " + advancedZip.fileName);
        System.out.println("File Size: " + advancedZip.fileSizeMB);
        System.out.println("Compressed Size: " + advancedZip.compressedSizeMB);
        System.out.println("Files: " + advancedZip.numberOfFiles);
        System.out.println("Time: " + advancedZip.processingTime);
        System.out.println("Encrypted: " + advancedZip.isEncrypted);
        System.out.println("Usage: " + advancedZip.usageType);
        System.out.println("Version: " + advancedZip.version);
        System.out.println("Software: " + advancedZip.originSoftware);
        System.out.println("Efficiency: " + advancedZip.efficiencyRate);
    }
}